/-
Copyright (c) 2026 Naganori Yamaguchi (https://github.com/n-yamaguchi-0729). All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Naganori Yamaguchi (assisted by OpenAI Codex)
-/

import Mathlib.Algebra.MonoidAlgebra.Lift
import Mathlib.Algebra.Module.BigOperators
import Mathlib.GroupTheory.Abelianization.Defs
import Mathlib.RingTheory.TwoSidedIdeal.Kernel
import Mathlib.RingTheory.TwoSidedIdeal.Operations
import Mathlib.Tactic.NoncommRing

set_option autoImplicit false

/-!
# Integral group-ring augmentation

This file develops the actual augmentation quotient `I_G / I_G²` used in
the transfer/augmentation comparison. It is kept separate from the transfer calculation so
that the group-ring identities can be reused in the proof of Witt's
transfer theorem.
-/

open scoped Pointwise

noncomputable section

namespace GroupTheory
namespace Augmentation

variable (G : Type*) [Group G]

/-- The integral group ring `ℤ[G]`. -/
abbrev IntegralGroupRing := MonoidAlgebra ℤ G

/-- The augmentation homomorphism `ℤ[G] → ℤ`. -/
def augmentation : IntegralGroupRing G →+* ℤ :=
  MonoidAlgebra.liftNCRingHom
    (RingHom.id ℤ) (1 : G →* ℤ)
    (fun _ _ => mul_comm _ _)

@[simp]
theorem augmentation_single (g : G) (n : ℤ) :
    augmentation G (MonoidAlgebra.single g n) = n := by
  change MonoidAlgebra.liftNC (RingHom.id ℤ : ℤ →+ ℤ)
    (1 : G → ℤ) (MonoidAlgebra.single g n) = n
  rw [MonoidAlgebra.liftNC_single]
  simp only [Pi.one_apply, mul_one]
  rfl

/-- The augmentation is the sum of the coefficients. -/
theorem augmentation_apply (x : IntegralGroupRing G) :
    augmentation G x = x.coeff.sum (fun _ n => n) := by
  classical
  conv_lhs => rw [← MonoidAlgebra.sum_coeff_single x]
  rw [map_finsuppSum]
  simp

/-- The augmentation ideal `I_G`. -/
def ideal : TwoSidedIdeal (IntegralGroupRing G) :=
  TwoSidedIdeal.ker (augmentation G)

theorem mem_ideal_iff (x : IntegralGroupRing G) :
    x ∈ ideal G ↔ augmentation G x = 0 := by
  rfl

/-- The underlying additive subgroup of a two-sided ideal. -/
def underlyingAddSubgroup
    {R : Type*} [NonUnitalNonAssocRing R]
    (I : TwoSidedIdeal R) : AddSubgroup R where
  carrier := I
  zero_mem' := I.zero_mem
  add_mem' := I.add_mem
  neg_mem' := I.neg_mem

/-- The product ideal `I_G²`, generated by products of two augmentation
elements. -/
def square : TwoSidedIdeal (IntegralGroupRing G) :=
  TwoSidedIdeal.span
    {z | ∃ x ∈ ideal G, ∃ y ∈ ideal G, z = x * y}

theorem square_le_ideal :
    square G ≤ ideal G := by
  rw [square, TwoSidedIdeal.span_le]
  rintro z ⟨x, hx, y, hy, rfl⟩
  exact (ideal G).mul_mem_right x y hx

/-- `I_G²` as an additive subgroup of `I_G`. -/
def squareInIdeal : AddSubgroup (ideal G) where
  carrier := {x | (x : IntegralGroupRing G) ∈ square G}
  zero_mem' := (square G).zero_mem
  add_mem' := (square G).add_mem
  neg_mem' := (square G).neg_mem

/-- Membership in `I_G²`, expressed after forgetting the ambient
augmentation-ideal subtype. -/
@[simp]
theorem mem_squareInIdeal_iff (x : ideal G) :
    x ∈ squareInIdeal G ↔
      (x : IntegralGroupRing G) ∈ square G :=
  Iff.rfl

/-- The augmentation quotient `I_G / I_G²`. -/
abbrev Quotient :=
  (ideal G) ⧸ squareInIdeal G

/-- The element `g - 1` of the augmentation ideal. -/
def deltaElement (g : G) : ideal G :=
  ⟨MonoidAlgebra.single g 1 -
      MonoidAlgebra.single (1 : G) 1, by
    rw [mem_ideal_iff, map_sub]
    simp⟩

@[simp]
theorem deltaElement_val (g : G) :
    (deltaElement G g : IntegralGroupRing G) =
      MonoidAlgebra.single g 1 -
        MonoidAlgebra.single (1 : G) 1 :=
  rfl

/-- The canonical expression of an augmentation-zero group-ring element
as a finite integral linear combination of the differences `g - 1`. -/
def deltaCombination (x : IntegralGroupRing G) :
    IntegralGroupRing G :=
  ∑ g ∈ x.coeff.support,
    x.coeff g •
      (MonoidAlgebra.single g 1 -
        MonoidAlgebra.single (1 : G) 1)

theorem deltaCombination_eq_of_mem_ideal
    (x : IntegralGroupRing G) (hx : x ∈ ideal G) :
    deltaCombination G x = x := by
  classical
  have hsum : x.coeff.sum (fun _ n => n) = 0 := by
    rw [← augmentation_apply]
    exact hx
  have hcoeff :
      ∑ g ∈ x.coeff.support, x.coeff g = 0 := by
    simpa [Finsupp.sum] using hsum
  have hfirst :
      ∑ g ∈ x.coeff.support,
          x.coeff g • MonoidAlgebra.single g (1 : ℤ) =
        x := by
    calc
      ∑ g ∈ x.coeff.support,
          x.coeff g • MonoidAlgebra.single g (1 : ℤ) =
          x.coeff.sum MonoidAlgebra.single := by
            rw [Finsupp.sum]
            apply Finset.sum_congr rfl
            intro g _
            simp [MonoidAlgebra.smul_single]
      _ = x := MonoidAlgebra.sum_coeff_single x
  unfold deltaCombination
  simp_rw [smul_sub]
  rw [Finset.sum_sub_distrib, hfirst]
  calc
    x -
        ∑ g ∈ x.coeff.support,
          x.coeff g •
            MonoidAlgebra.single (1 : G) (1 : ℤ) =
      x -
        (∑ g ∈ x.coeff.support, x.coeff g) •
          MonoidAlgebra.single (1 : G) (1 : ℤ) := by
            rw [Finset.sum_smul]
    _ = x := by rw [hcoeff, zero_smul, sub_zero]

/-- The same finite combination, now intrinsically valued in `I_G`. -/
def deltaCombinationElement (x : IntegralGroupRing G) :
    ideal G :=
  ∑ g ∈ x.coeff.support, x.coeff g • deltaElement G g

@[simp]
theorem deltaCombinationElement_val
    (x : IntegralGroupRing G) :
    (deltaCombinationElement G x : IntegralGroupRing G) =
      deltaCombination G x :=
  by
    simp [deltaCombinationElement, deltaCombination]

theorem deltaCombinationElement_eq_of_mem_ideal
    (x : IntegralGroupRing G) (hx : x ∈ ideal G) :
    deltaCombinationElement G x = ⟨x, hx⟩ := by
  apply Subtype.ext
  rw [deltaCombinationElement_val]
  exact deltaCombination_eq_of_mem_ideal G x hx

/-- The class of `g - 1` in `I_G / I_G²`. -/
def deltaClass (g : G) : Quotient G :=
  QuotientAddGroup.mk' (squareInIdeal G) (deltaElement G g)

@[simp]
theorem deltaClass_one :
    deltaClass G 1 = 0 := by
  apply (QuotientAddGroup.eq_zero_iff _).2
  rw [mem_squareInIdeal_iff]
  simpa only [deltaElement_val, sub_self] using (square G).zero_mem

/-- Modulo `I_G²`, the identity `δ(gh)=δg+δh` makes the augmentation
class a homomorphism from `G` to the additive quotient. -/
theorem deltaClass_mul (g h : G) :
    deltaClass G (g * h) =
      deltaClass G g + deltaClass G h := by
  apply (QuotientAddGroup.eq_iff_sub_mem).2
  rw [mem_squareInIdeal_iff]
  have hg : (deltaElement G g : IntegralGroupRing G) ∈ ideal G :=
    (deltaElement G g).property
  have hh : (deltaElement G h : IntegralGroupRing G) ∈ ideal G :=
    (deltaElement G h).property
  have hprod :
      (deltaElement G g : IntegralGroupRing G) *
          (deltaElement G h : IntegralGroupRing G) ∈
        square G :=
    TwoSidedIdeal.subset_span ⟨_, hg, _, hh, rfl⟩
  convert hprod using 1
  show
    (deltaElement G (g * h) : IntegralGroupRing G) -
        ((deltaElement G g : IntegralGroupRing G) +
          (deltaElement G h : IntegralGroupRing G)) =
      (deltaElement G g : IntegralGroupRing G) *
        (deltaElement G h : IntegralGroupRing G)
  simp only [deltaElement_val]
  have hsingle :
      MonoidAlgebra.single (g * h) (1 : ℤ) =
        MonoidAlgebra.single g 1 *
          MonoidAlgebra.single h 1 := by
    simp
  rw [hsingle]
  rw [← MonoidAlgebra.one_def]
  noncomm_ring

/-- Multiplicative spelling of `g ↦ δg`, convenient for passage through
the abelianization. -/
def deltaMonoidHom :
    G →* Multiplicative (Quotient G) where
  toFun g := Multiplicative.ofAdd (deltaClass G g)
  map_one' := by
    apply Multiplicative.toAdd.injective
    exact deltaClass_one G
  map_mul' g h := by
    apply Multiplicative.toAdd.injective
    exact deltaClass_mul G g h

/-- The augmentation class factors canonically through `Gᵃᵇ`. -/
def deltaAbelianization :
    Abelianization G →* Multiplicative (Quotient G) :=
  Abelianization.lift (deltaMonoidHom G)

@[simp]
theorem deltaAbelianization_of (g : G) :
    deltaAbelianization G (Abelianization.of g) =
      Multiplicative.ofAdd (deltaClass G g) :=
  rfl

/-- A finite preimage in `Gᵃᵇ` for the coefficient combination attached
to a group-ring element. -/
def deltaPreimage (x : IntegralGroupRing G) :
    Abelianization G :=
  ∏ g ∈ x.coeff.support,
    Abelianization.of g ^ x.coeff g

theorem deltaAbelianization_deltaPreimage
    (x : IntegralGroupRing G) (hx : x ∈ ideal G) :
    deltaAbelianization G (deltaPreimage G x) =
      Multiplicative.ofAdd
        (QuotientAddGroup.mk' (squareInIdeal G) ⟨x, hx⟩) := by
  apply Multiplicative.toAdd.injective
  show
    Multiplicative.toAdd
        (deltaAbelianization G (deltaPreimage G x)) =
      QuotientAddGroup.mk' (squareInIdeal G) ⟨x, hx⟩
  rw [deltaPreimage, map_prod]
  simp_rw [map_zpow, deltaAbelianization_of]
  show
    ∑ g ∈ x.coeff.support,
        x.coeff g • deltaClass G g =
      QuotientAddGroup.mk' (squareInIdeal G) ⟨x, hx⟩
  show
    ∑ g ∈ x.coeff.support,
        x.coeff g •
          QuotientAddGroup.mk' (squareInIdeal G)
            (deltaElement G g) =
      QuotientAddGroup.mk' (squareInIdeal G) ⟨x, hx⟩
  simp_rw [← map_zsmul]
  rw [← map_sum]
  show
    QuotientAddGroup.mk' (squareInIdeal G)
        (deltaCombinationElement G x) =
      QuotientAddGroup.mk' (squareInIdeal G) ⟨x, hx⟩
  rw [deltaCombinationElement_eq_of_mem_ideal G x hx]

/-- The augmentation map `Gᵃᵇ → I_G/I_G²` is surjective. -/
theorem deltaAbelianization_surjective :
    Function.Surjective (deltaAbelianization G) := by
  intro q
  change
    ∃ a : Abelianization G,
      deltaAbelianization G a =
        Multiplicative.ofAdd (Multiplicative.toAdd q)
  refine
    QuotientAddGroup.induction_on
      (Multiplicative.toAdd q) ?_
  intro x
  exact
    ⟨deltaPreimage G x.1,
      deltaAbelianization_deltaPreimage
        G x.1 x.2⟩

/-- A coefficient at `g` contributes that many copies of the class of
`g` in the abelianization. -/
def coefficientToAbelianization (g : G) :
    ℤ →+ Additive (Abelianization G) where
  toFun n := n • Additive.ofMul (Abelianization.of g)
  map_zero' := zero_zsmul _
  map_add' m n := add_zsmul _ m n

/-- Linearization of the integral group ring in the abelianization. -/
def linearization :
    IntegralGroupRing G →+ Additive (Abelianization G) :=
  ((Finsupp.liftAddHom
      (α := G) (M := ℤ)
      (N := Additive (Abelianization G)))
      (coefficientToAbelianization G)).comp
    MonoidAlgebra.coeffAddEquiv.toAddMonoidHom

@[simp]
theorem linearization_single (g : G) (n : ℤ) :
    linearization G (MonoidAlgebra.single g n) =
      n • Additive.ofMul (Abelianization.of g) := by
  simp [linearization, coefficientToAbelianization]

@[simp]
theorem linearization_deltaElement (g : G) :
    linearization G (deltaElement G g) =
      Additive.ofMul (Abelianization.of g) := by
  simp [deltaElement, linearization_single]

/-- Products of two basic augmentation differences vanish after
linearization. -/
theorem linearization_deltaElement_mul_deltaElement
    (g h : G) :
    linearization G
        ((deltaElement G g : IntegralGroupRing G) *
          (deltaElement G h : IntegralGroupRing G)) =
      0 := by
  simp [deltaElement, map_sub,
    MonoidAlgebra.single_mul_single, mul_sub, sub_mul]

/-- Linearization kills a product of two augmentation-zero elements. -/
theorem linearization_mul_eq_zero_of_mem_ideal
    (x y : IntegralGroupRing G)
    (hx : x ∈ ideal G) (hy : y ∈ ideal G) :
    linearization G (x * y) = 0 := by
  rw [← deltaCombination_eq_of_mem_ideal G x hx,
    ← deltaCombination_eq_of_mem_ideal G y hy]
  simp only [deltaCombination]
  rw [Finset.sum_mul]
  simp_rw [Finset.mul_sum]
  rw [map_sum]
  apply Finset.sum_eq_zero
  intro g hg
  rw [map_sum]
  apply Finset.sum_eq_zero
  intro h hh
  rw [smul_mul_smul_comm, map_zsmul,
    ← deltaElement_val, ← deltaElement_val,
    linearization_deltaElement_mul_deltaElement, smul_zero]

/-- Linearization vanishes on the square of the augmentation ideal. -/
theorem linearization_eq_zero_of_mem_square
    (z : IntegralGroupRing G) (hz : z ∈ square G) :
    linearization G z = 0 := by
  have hstrong :
      ∀ z : IntegralGroupRing G,
        z ∈ square G →
          ∀ a b : IntegralGroupRing G,
            linearization G (a * z * b) = 0 := by
    intro z hz
    rw [square] at hz
    refine TwoSidedIdeal.span_induction
      (s :=
        {z | ∃ x ∈ ideal G, ∃ y ∈ ideal G, z = x * y})
      (p := fun z _ =>
        ∀ a b : IntegralGroupRing G,
          linearization G (a * z * b) = 0)
      ?_ ?_ ?_ ?_ ?_ ?_ hz
    · rintro z ⟨x, hx, y, hy, rfl⟩ a b
      simpa only [mul_assoc] using
        linearization_mul_eq_zero_of_mem_ideal G
          (a * x) (y * b)
          ((ideal G).mul_mem_left a x hx)
          ((ideal G).mul_mem_right y b hy)
    · intro a b
      simp
    · intro x y hx hy hlinx hliny a b
      simp [mul_add, add_mul, hlinx a b, hliny a b]
    · intro x hx hlin a b
      simp [hlin a b]
    · intro c x hx hlin a b
      simpa only [mul_assoc] using hlin (a * c) b
    · intro c x hx hlin a b
      simpa only [mul_assoc] using hlin a (c * b)
  simpa using hstrong z hz 1 1

/-- Linearization restricted to the augmentation ideal. -/
def linearizationOnIdeal :
    ideal G →+ Additive (Abelianization G) where
  toFun x := linearization G (x : IntegralGroupRing G)
  map_zero' := (linearization G).map_zero
  map_add' x y := (linearization G).map_add x y

/-- The inverse linearization map on `I_G/I_G²`. -/
def quotientLinearization :
    Quotient G →+ Additive (Abelianization G) :=
  QuotientAddGroup.lift
    (squareInIdeal G) (linearizationOnIdeal G) (by
      intro x hx
      apply AddMonoidHom.mem_ker.2
      exact linearization_eq_zero_of_mem_square G x hx)

@[simp]
theorem quotientLinearization_deltaClass (g : G) :
    quotientLinearization G (deltaClass G g) =
      Additive.ofMul (Abelianization.of g) := by
  exact linearization_deltaElement G g

/-- Multiplicative spelling of inverse linearization. -/
def quotientLinearizationMonoidHom :
    Multiplicative (Quotient G) →* Abelianization G :=
  (quotientLinearization G).toMultiplicativeLeft

@[simp]
theorem quotientLinearizationMonoidHom_deltaClass (g : G) :
    quotientLinearizationMonoidHom G
        (Multiplicative.ofAdd (deltaClass G g)) =
      Abelianization.of g := by
  exact congrArg Additive.toMul
    (quotientLinearization_deltaClass G g)

/-- Inverse linearization is a left inverse to the augmentation-class
map. -/
theorem quotientLinearizationMonoidHom_deltaAbelianization
    (a : Abelianization G) :
    quotientLinearizationMonoidHom G
        (deltaAbelianization G a) =
      a := by
  refine QuotientGroup.induction_on a ?_
  intro g
  exact quotientLinearizationMonoidHom_deltaClass G g

/-- The canonical augmentation-class map is injective. -/
theorem deltaAbelianization_injective :
    Function.Injective (deltaAbelianization G) := by
  intro a b hab
  have h := congrArg (quotientLinearizationMonoidHom G) hab
  rw [quotientLinearizationMonoidHom_deltaAbelianization G a,
    quotientLinearizationMonoidHom_deltaAbelianization G b] at h
  exact h

/-- The classical canonical isomorphism
`Gᵃᵇ ≃ I_G/I_G²`, in multiplicative notation on the target. -/
noncomputable def deltaAbelianizationEquiv :
    Abelianization G ≃* Multiplicative (Quotient G) :=
  MulEquiv.ofBijective (deltaAbelianization G)
    ⟨deltaAbelianization_injective G,
      deltaAbelianization_surjective G⟩

@[simp]
theorem deltaAbelianizationEquiv_apply (a : Abelianization G) :
    deltaAbelianizationEquiv G a =
      deltaAbelianization G a :=
  rfl

@[simp]
theorem deltaAbelianizationEquiv_of (g : G) :
    deltaAbelianizationEquiv G (Abelianization.of g) =
      Multiplicative.ofAdd (deltaClass G g) :=
  rfl

/-- Every commutator has zero augmentation class modulo `I_G²`. -/
theorem deltaClass_eq_zero_of_mem_commutator
    {g : G} (hg : g ∈ commutator G) :
    deltaClass G g = 0 := by
  have hker :
      g ∈ (deltaMonoidHom G).ker :=
    Abelianization.commutator_subset_ker
      (deltaMonoidHom G) hg
  have hone : deltaMonoidHom G g = 1 :=
    MonoidHom.mem_ker.mp hker
  exact congrArg Multiplicative.toAdd hone

end Augmentation
end GroupTheory
