/-
Copyright (c) 2026 Naganori Yamaguchi (https://github.com/n-yamaguchi-0729). All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Naganori Yamaguchi (assisted by OpenAI Codex)
-/

import Mathlib.GroupTheory.Abelianization.Defs
import Mathlib.GroupTheory.QuotientGroup.Basic

set_option autoImplicit false

/-!
# Quotients represented by a supporting subgroup

If two subgroups generate a commutative group, every class modulo the
second subgroup has a representative in the first.  This is the precise
group-theoretic comparison used when a sufficiently large group of
supported ideles represents the full idele class group.
-/

noncomputable section

variable {G : Type*} [CommGroup G]

/-- If `S` and `P` generate `G`, inclusion of `S` identifies
`S / (S ∩ P)` with `G / P`. -/
noncomputable def subgroupQuotientEquivQuotientOfSupEqTop
    (S P : Subgroup G)
    (hSP : S ⊔ P = ⊤) :
    S ⧸ P.subgroupOf S ≃* G ⧸ P := by
  let eSup : (S ⊔ P : Subgroup G) ≃* G :=
    MulEquiv.ofBijective (S ⊔ P).subtype
      ⟨Subtype.val_injective, fun x =>
        ⟨⟨x, by rw [hSP]; exact Subgroup.mem_top x⟩, rfl⟩⟩
  exact
    (QuotientGroup.quotientInfEquivProdNormalQuotient S P).trans <|
    QuotientGroup.congr
      (P.subgroupOf (S ⊔ P)) P eSup (by
        ext x
        constructor
        · rintro ⟨a, ha, rfl⟩
          exact ha
        · intro hx
          refine ⟨⟨x, ?_⟩, hx, rfl⟩
          rw [hSP]
          exact Subgroup.mem_top x)

@[simp]
theorem subgroupQuotientEquivQuotientOfSupEqTop_mk
    (S P : Subgroup G)
    (hSP : S ⊔ P = ⊤)
    (s : S) :
    subgroupQuotientEquivQuotientOfSupEqTop S P hSP
        (QuotientGroup.mk' (P.subgroupOf S) s) =
      QuotientGroup.mk' P (s : G) := by
  simp [subgroupQuotientEquivQuotientOfSupEqTop,
    QuotientGroup.quotientInfEquivProdNormalQuotient,
    QuotientGroup.quotientInfEquivProdNormalizerQuotient,
    QuotientGroup.quotientKerEquivOfSurjective,
    QuotientGroup.quotientKerEquivOfRightInverse,
    QuotientGroup.kerLift_mk]
  have ofBijective_apply'
      (f : (S ⊔ P : Subgroup G) →* G)
      (hf : Function.Injective f ∧ Function.Surjective f)
      (x : (S ⊔ P : Subgroup G)) :
      (MulEquiv.ofBijective f hf) x = f x :=
    MulEquiv.ofBijective_apply f hf x
  rw [ofBijective_apply']
  rfl

namespace Subgroup

universe u

variable {Gamma : Type u} [Group Gamma]

/-- The inverse image of the image of a subgroup in the abelianization is
the subgroup generated by it and the commutator subgroup. -/
theorem comap_map_abelianization_eq_sup_commutator (H : Subgroup Gamma) :
    (H.map (Abelianization.of : Gamma →* Abelianization Gamma)).comap
        (Abelianization.of : Gamma →* Abelianization Gamma) =
      H ⊔ _root_.commutator Gamma := by
  rw [Subgroup.comap_map_eq, Abelianization.ker_of]

/-- Adjoining the commutator subgroup to any subgroup produces a normal
subgroup. -/
instance normal_sup_commutator (H : Subgroup Gamma) :
    (H ⊔ _root_.commutator Gamma).Normal := by
  rw [← H.comap_map_abelianization_eq_sup_commutator]
  infer_instance

/-- Quotienting a group by a subgroup together with the commutator subgroup
agrees with quotienting its abelianization by the image of that subgroup. -/
noncomputable def quotientSupCommutatorEquivMapAbelianization
    (H : Subgroup Gamma) :
    Gamma ⧸ (H ⊔ _root_.commutator Gamma) ≃*
      Abelianization Gamma ⧸
        H.map (Abelianization.of : Gamma →* Abelianization Gamma) := by
  let phi : Gamma →*
      Abelianization Gamma ⧸
        H.map (Abelianization.of : Gamma →* Abelianization Gamma) :=
    (QuotientGroup.mk'
      (H.map (Abelianization.of : Gamma →* Abelianization Gamma))).comp
        Abelianization.of
  have hphiKer : phi.ker = H ⊔ _root_.commutator Gamma := by
    simpa only [phi, ← MonoidHom.comap_ker, QuotientGroup.ker_mk'] using
      H.comap_map_abelianization_eq_sup_commutator
  have hphiSurjective : Function.Surjective phi := by
    exact (QuotientGroup.mk'_surjective _).comp
      (QuotientGroup.mk'_surjective (_root_.commutator Gamma))
  exact
    (QuotientGroup.quotientMulEquivOfEq hphiKer.symm).trans
      (QuotientGroup.quotientKerEquivOfSurjective phi hphiSurjective)

@[simp]
theorem quotientSupCommutatorEquivMapAbelianization_mk
    (H : Subgroup Gamma) (g : Gamma) :
    H.quotientSupCommutatorEquivMapAbelianization
        (QuotientGroup.mk' (H ⊔ _root_.commutator Gamma) g) =
      QuotientGroup.mk'
        (H.map (Abelianization.of : Gamma →* Abelianization Gamma))
        (Abelianization.of g) := by
  rfl

end Subgroup
