/-
Copyright (c) 2026 Naganori Yamaguchi (https://github.com/n-yamaguchi-0729). All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Naganori Yamaguchi (assisted by OpenAI Codex)
-/

import ValuedFieldTheory.LocalField.Padic.PrincipalUnits
import ValuedFieldTheory.LocalField.Padic.Cyclotomic.TotallyRamified.Existence
import ClassFieldTheory.LocalClassFieldTheory.Finite.UnramifiedConductor
import ValuedFieldTheory.Valuation.LocalRingEquiv

set_option autoImplicit false

/-!
# Norm subgroups of p-adic prime-power cyclotomic extensions

For a primitive `p ^ (k + 1)`-st root of unity generating `L / ℚ_p`,
the norm subgroup is exactly the subgroup generated by `p` and the
`(k + 1)`-st principal units.  The odd and dyadic calculations are kept
separate before being combined in the final theorem.
-/

noncomputable section

open scoped ValuativeRel WithZero

namespace LocalClassFieldTheory

open LocalFieldTheory
open LocalFieldTheory.Padic
open LocalFieldTheory.IsNonarchimedeanLocalField
open ValuationTheory

variable (p : ℕ) [Fact p.Prime]

/-- For odd `p`, the `(k+1)`-st principal units of `ℚ_p` are norms from a
primitive `p^(k+1)`-st cyclotomic extension. -/
theorem fieldPrincipalUnits_le_normSubgroup_cyclotomic_odd
    {k : ℕ} (hp2 : p ≠ 2)
    {L : Type} [Field L] [Algebra ℚ_[p] L]
    (zeta : L) (hzeta : IsPrimitiveRoot zeta (p ^ (k + 1)))
    (hgen : Algebra.adjoin ℚ_[p] ({zeta} : Set L) = ⊤) :
    LocalFieldTheory.fieldPrincipalUnits ℚ_[p] (k + 1) ≤ localNormSubgroup ℚ_[p] L := by
  let v := LocalFieldTheory.DiscreteValuationField.Examples.Qp.padicDVRValuation p
  let F :=
    LocalFieldTheory.DiscreteValuationField.MultiplicativeIntegerValuation.completeDVFOfWithZeroValuation v
  let eO : 𝒪[ℚ_[p]] ≃+* F.valuationSubring :=
    integerRingEquivPadicDVRValuationSubring p
  let EU : 𝒪[ℚ_[p]]ˣ ≃* F.valuationSubringˣ :=
    Units.mapEquiv eO.toMulEquiv
  rintro x ⟨u, hu, rfl⟩
  have huD : EU u ∈ LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F (k + 1) := by
    change Units.mapEquiv
        (integerRingEquivPadicDVRValuationSubring p).toMulEquiv u ∈
      LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup
        (LocalFieldTheory.DiscreteValuationField.Examples.Qp.padicCompleteDVF p)
        (k + 1)
    exact (unitsMapEquiv_mem_higherPrincipalUnitGroup_iff p (k + 1) u).2 hu
  let uD : LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F (k + 1) := ⟨EU u, huD⟩
  obtain ⟨rD, hrD⟩ :=
    padicDVR_higherPrincipalUnit_degree_is_power_odd p hp2 k uD
  let rO : 𝒪[ℚ_[p]]ˣ := EU.symm (rD : F.valuationSubringˣ)
  have hrO : rO ∈ principalUnits ℚ_[p] 1 := by
    apply (unitsMapEquiv_mem_higherPrincipalUnitGroup_iff p 1 rO).1
    have hmapF : EU rO ∈ LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F 1 := by
      simpa only [rO, MulEquiv.apply_symm_apply] using rD.property
    have hmap :
        Units.mapEquiv
            (integerRingEquivPadicDVRValuationSubring p).toMulEquiv rO ∈
          LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup (LocalFieldTheory.DiscreteValuationField.Examples.Qp.padicCompleteDVF p) 1 := by
      change EU rO ∈ LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F 1
      exact hmapF
    exact hmap
  let r : ℚ_[p]ˣ := integerUnitsToFieldUnits ℚ_[p] rO
  have hrO_pow : rO ^ ((p - 1) * p ^ k) = u := by
    apply EU.injective
    simpa [rO, uD] using hrD
  have hr_pow : r ^ ((p - 1) * p ^ k) = integerUnitsToFieldUnits ℚ_[p] u := by
    calc
      r ^ ((p - 1) * p ^ k) =
          integerUnitsToFieldUnits ℚ_[p] (rO ^ ((p - 1) * p ^ k)) := by
        exact (map_pow (integerUnitsToFieldUnits ℚ_[p]) rO ((p - 1) * p ^ k)).symm
      _ = integerUnitsToFieldUnits ℚ_[p] u := congrArg _ hrO_pow
  have hnorm := LocalFieldTheory.DiscreteValuationField.fieldNormSubgroup_pow_finrank_mem ℚ_[p] L r
  rw [AlgebraicNumberTheory.Valuations.padicCyclotomic_finrank_eq_prime_sub_one_mul_pow
    zeta hzeta hgen] at hnorm
  rw [hr_pow] at hnorm
  simpa [LocalFieldTheory.DiscreteValuationField.fieldNormSubgroup,
    localNormSubgroup] using hnorm

/-- The prime element `p` is a norm from a primitive prime-power cyclotomic
extension of `ℚ_p`. -/
theorem padicPrimeUnit_mem_normSubgroup_cyclotomic
    {k : ℕ} {L : Type} [Field L] [Algebra ℚ_[p] L]
    (zeta : L) (hzeta : IsPrimitiveRoot zeta (p ^ (k + 1)))
    (hgen : Algebra.adjoin ℚ_[p] ({zeta} : Set L) = ⊤) :
    padicPrimeUnit p ∈ localNormSubgroup ℚ_[p] L := by
  have horder : 1 < p ^ (k + 1) :=
    Nat.one_lt_pow (Nat.succ_ne_zero k) (Fact.out : Nat.Prime p).one_lt
  have hne : (1 - zeta : L) ≠ 0 :=
    sub_ne_zero.mpr (Ne.symm (hzeta.ne_one horder))
  let y : Lˣ := Units.mk0 (1 - zeta) hne
  apply MonoidHom.mem_range.mpr
  refine ⟨y, ?_⟩
  apply Units.ext
  change Algebra.norm ℚ_[p] (1 - zeta) = (p : ℚ_[p])
  exact AlgebraicNumberTheory.Valuations.padicCyclotomic_norm_one_sub_primitiveRoot_eq_prime
    zeta hzeta hgen

/-- For odd `p`, the standard subgroup generated by `p` and `U^(k+1)` is
contained in the cyclotomic norm subgroup. -/
theorem uniformizerPrincipalSubgroup_le_normSubgroup_cyclotomic_odd
    {k : ℕ} (hp2 : p ≠ 2)
    {L : Type} [Field L] [Algebra ℚ_[p] L]
    (zeta : L) (hzeta : IsPrimitiveRoot zeta (p ^ (k + 1)))
    (hgen : Algebra.adjoin ℚ_[p] ({zeta} : Set L) = ⊤) :
    LocalFieldTheory.uniformizerPrincipalSubgroup ℚ_[p] (padicPrimeUnit p) 1 (k + 1) ≤
      localNormSubgroup ℚ_[p] L := by
  rw [LocalFieldTheory.uniformizerPrincipalSubgroup]
  apply sup_le
  · rw [Subgroup.zpowers_le]
    simpa using
      padicPrimeUnit_mem_normSubgroup_cyclotomic p zeta hzeta hgen
  · exact fieldPrincipalUnits_le_normSubgroup_cyclotomic_odd
      p hp2 zeta hzeta hgen

/-- For odd `p`, the norm subgroup of a primitive `p^(k+1)`-st cyclotomic
extension is exactly the subgroup generated by `p` and `U^(k+1)`. -/
theorem localNormSubgroup_eq_uniformizerPrincipalSubgroup_cyclotomicPrimePower_odd
    {k : ℕ} (hp2 : p ≠ 2)
    {L : Type} [Field L] [Algebra ℚ_[p] L]
    (zeta : L) (hzeta : IsPrimitiveRoot zeta (p ^ (k + 1)))
    (hgen : Algebra.adjoin ℚ_[p] ({zeta} : Set L) = ⊤) :
    localNormSubgroup ℚ_[p] L =
      LocalFieldTheory.uniformizerPrincipalSubgroup ℚ_[p] (padicPrimeUnit p) 1 (k + 1) := by
  let : IsNonarchimedeanLocalField ℚ_[p] :=
    padicIsNonarchimedeanLocalField p
  let n := p ^ (k + 1)
  let : NeZero n :=
    ⟨pow_ne_zero _ (Fact.out : Nat.Prime p).ne_zero⟩
  let : IsCyclotomicExtension {n} ℚ_[p] L := by
    simpa [n] using
      AlgebraicNumberTheory.Valuations.padic_isCyclotomicExtension_of_primitiveRoot_adjoin_eq_top zeta hzeta hgen
  let : FiniteDimensional ℚ_[p] L :=
    IsCyclotomicExtension.finiteDimensional {n} ℚ_[p] L
  let : IsAbelianGalois ℚ_[p] L :=
    IsCyclotomicExtension.isAbelianGalois {n} ℚ_[p] L
  let H :=
    LocalFieldTheory.uniformizerPrincipalSubgroup ℚ_[p] (padicPrimeUnit p) 1 (k + 1)
  let N := localNormSubgroup ℚ_[p] L
  have hHinv : H =
      LocalFieldTheory.uniformizerPrincipalSubgroup ℚ_[p]
        (padicPrimeUnit p)⁻¹ 1 (k + 1) := by
    simp [H, LocalFieldTheory.uniformizerPrincipalSubgroup, Subgroup.zpowers_inv]
  have hcardH : Nat.card (ℚ_[p]ˣ ⧸ H) = (p - 1) * p ^ k := by
    rw [hHinv]
    exact nat_card_fieldUnitsUniformizerPrincipalQuot_padic_succ p k
  have hindexH : H.index = (p - 1) * p ^ k := by
    rw [Subgroup.index_eq_card]
    exact hcardH
  have hcardN : Nat.card (NormQuotient ℚ_[p] L) = (p - 1) * p ^ k := by
    calc
      Nat.card (NormQuotient ℚ_[p] L) = Module.finrank ℚ_[p] L := by
        exact card_normQuotient_eq_finrank_of_isAbelianGalois ℚ_[p] L
      _ = (p - 1) * p ^ k :=
        AlgebraicNumberTheory.Valuations.padicCyclotomic_finrank_eq_prime_sub_one_mul_pow
          zeta hzeta hgen
  have hindexN : N.index = (p - 1) * p ^ k := by
    rw [Subgroup.index_eq_card]
    exact hcardN
  have hdpos : 0 < (p - 1) * p ^ k :=
    Nat.mul_pos (Nat.sub_pos_of_lt (Fact.out : Nat.Prime p).one_lt)
      (pow_pos (Fact.out : Nat.Prime p).pos k)
  let : H.FiniteIndex := ⟨by
    rw [hindexH]
    exact Nat.ne_of_gt hdpos⟩
  have hHN : H ≤ N := by
    exact uniformizerPrincipalSubgroup_le_normSubgroup_cyclotomic_odd
      p hp2 zeta hzeta hgen
  apply Eq.symm
  apply le_antisymm hHN
  by_contra hNH
  have hne : H ≠ N := by
    intro heq
    apply hNH
    rw [heq]
  have hstrict : H < N := lt_of_le_of_ne hHN hne
  have hi := Subgroup.index_strictAnti hstrict
  rw [hindexH, hindexN] at hi
  exact (Nat.lt_irrefl _ hi)


/-- The minimal polynomial of `2 + i`, for a primitive fourth root `i`, is
the translated fourth cyclotomic polynomial. -/
theorem minpoly_two_add_primitiveFourthRoot
    {L : Type*} [Field L] [Algebra ℚ_[2] L]
    (i : L) (hi : IsPrimitiveRoot i 4) :
    minpoly ℚ_[2] ((2 : L) + i) =
      (Polynomial.cyclotomic 4 ℚ_[2]).comp
        (Polynomial.X - Polynomial.C (2 : ℚ_[2])) := by
  let : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  let : NeZero (4 : ℚ_[2]) := ⟨by norm_num⟩
  have hirr :
      Irreducible (Polynomial.cyclotomic 4 ℚ_[2]) := by
    simpa using
      AlgebraicNumberTheory.Valuations.padicCyclotomicPolynomial_irreducible_prime_pow_succ 2 1
  have hadd :
      (2 : L) + i = i + algebraMap ℚ_[2] L (2 : ℚ_[2]) := by
    rw [map_ofNat (algebraMap ℚ_[2] L) 2]
    exact add_comm _ _
  rw [hadd, minpoly.add_algebraMap, ← hi.minpoly_eq_cyclotomic_of_irreducible hirr]


/-- Over `ℚ₂`, the fourth cyclotomic polynomial is `X² + 1`. -/
theorem cyclotomic_four_padic :
    Polynomial.cyclotomic 4 ℚ_[2] =
      Polynomial.X ^ 2 + 1 := by
  rw [show 4 = 2 ^ (1 + 1) by norm_num,
    Polynomial.cyclotomic_prime_pow_eq_geom_sum Nat.prime_two]
  norm_num [Finset.sum_range_succ]
  ac_rfl


/-- The norm of `2 + i` from its simple extension over `ℚ₂` is `5`. -/
theorem norm_adjoin_two_add_primitiveFourthRoot
    {L : Type*} [Field L] [Algebra ℚ_[2] L]
    (i : L) (hi : IsPrimitiveRoot i 4) :
    Algebra.norm ℚ_[2]
        (IntermediateField.AdjoinSimple.gen ℚ_[2] ((2 : L) + i)) =
      (5 : ℚ_[2]) := by
  let j : L := (2 : L) + i
  have hj : j = algebraMap ℚ_[2] L (2 : ℚ_[2]) + i := by
    dsimp [j]
    rw [map_ofNat (algebraMap ℚ_[2] L) 2]
  have hjint : IsIntegral ℚ_[2] j := by
    rw [hj]
    exact (isIntegral_algebraMap :
      IsIntegral ℚ_[2] (algebraMap ℚ_[2] L (2 : ℚ_[2]))).add
        ((hi.isIntegral (by norm_num)).tower_top)
  let E : IntermediateField ℚ_[2] L := IntermediateField.adjoin ℚ_[2] {j}
  let pb : PowerBasis ℚ_[2] E :=
    IntermediateField.adjoin.powerBasis hjint
  change Algebra.norm ℚ_[2] pb.gen = (5 : ℚ_[2])
  rw [Algebra.PowerBasis.norm_gen_eq_coeff_zero_minpoly]
  simp only [pb, E, IntermediateField.adjoin.powerBasis_dim,
    IntermediateField.adjoin.powerBasis_gen, IntermediateField.minpoly_gen]
  rw [minpoly_two_add_primitiveFourthRoot i hi]
  rw [cyclotomic_four_padic]
  rw [Polynomial.natDegree_comp]
  rw [show (1 : Polynomial ℚ_[2]) = Polynomial.C 1 by simp,
    Polynomial.natDegree_X_pow_add_C, Polynomial.natDegree_X_sub_C]
  rw [
    Polynomial.coeff_zero_eq_eval_zero, Polynomial.eval_comp]
  norm_num

/-- In a primitive `2^(m+2)`-st cyclotomic extension, the norm of
`2 + ζ^(2^m)` is `5^(2^m)`. -/
theorem norm_two_add_fourthRoot_cyclotomic_two
    (m : ℕ) {L : Type*} [Field L] [Algebra ℚ_[2] L]
    (zeta : L) (hzeta : IsPrimitiveRoot zeta (2 ^ (m + 2)))
    (hgen : Algebra.adjoin ℚ_[2] ({zeta} : Set L) = ⊤) :
    Algebra.norm ℚ_[2] ((2 : L) + zeta ^ (2 ^ m)) =
      (5 : ℚ_[2]) ^ (2 ^ m) := by
  let : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  let n := 2 ^ (m + 2)
  let : NeZero n := ⟨pow_ne_zero _ (by norm_num)⟩
  let : IsCyclotomicExtension {n} ℚ_[2] L := by
    simpa [n, Nat.add_assoc] using
      AlgebraicNumberTheory.Valuations.padic_isCyclotomicExtension_of_primitiveRoot_adjoin_eq_top
        (p := 2) (k := m + 1) zeta hzeta hgen
  let : FiniteDimensional ℚ_[2] L :=
    IsCyclotomicExtension.finiteDimensional {n} ℚ_[2] L
  let i : L := zeta ^ (2 ^ m)
  have hi : IsPrimitiveRoot i 4 := by
    apply hzeta.pow (by positivity)
    rw [show m + 2 = m + 2 by rfl, pow_add]
    norm_num
  let j : L := (2 : L) + i
  have hj : j = algebraMap ℚ_[2] L (2 : ℚ_[2]) + i := by
    dsimp [j]
    rw [map_ofNat (algebraMap ℚ_[2] L) 2]
  have hjint : IsIntegral ℚ_[2] j := by
    rw [hj]
    exact (isIntegral_algebraMap :
      IsIntegral ℚ_[2] (algebraMap ℚ_[2] L (2 : ℚ_[2]))).add
        ((hi.isIntegral (by norm_num)).tower_top)
  let E : IntermediateField ℚ_[2] L := IntermediateField.adjoin ℚ_[2] {j}
  have hfinE : Module.finrank ℚ_[2] E = 2 := by
    rw [IntermediateField.adjoin.finrank hjint]
    rw [minpoly_two_add_primitiveFourthRoot i hi]
    rw [cyclotomic_four_padic, Polynomial.natDegree_comp]
    rw [show (1 : Polynomial ℚ_[2]) = Polynomial.C 1 by simp,
      Polynomial.natDegree_X_pow_add_C, Polynomial.natDegree_X_sub_C]
  have hfinL : Module.finrank ℚ_[2] L = 2 ^ (m + 1) := by
    simpa [Nat.add_assoc] using
      AlgebraicNumberTheory.Valuations.padicCyclotomic_finrank_eq_prime_sub_one_mul_pow
        (p := 2) (k := m + 1) zeta hzeta hgen
  have hmul :
      2 * Module.finrank E L = 2 * (2 ^ m) := by
    calc
      2 * Module.finrank E L =
          Module.finrank ℚ_[2] E * Module.finrank E L := by rw [hfinE]
      _ = Module.finrank ℚ_[2] L :=
        Module.finrank_mul_finrank ℚ_[2] E L
      _ = 2 ^ (m + 1) := hfinL
      _ = 2 * (2 ^ m) := by rw [pow_succ]; ac_rfl
  have hfinRel : Module.finrank E L = 2 ^ m :=
    Nat.eq_of_mul_eq_mul_left (by norm_num) hmul
  calc
    Algebra.norm ℚ_[2] ((2 : L) + zeta ^ (2 ^ m)) =
        Algebra.norm ℚ_[2] j := by rfl
    _ = Algebra.norm ℚ_[2]
          (IntermediateField.AdjoinSimple.gen ℚ_[2] j) ^
        Module.finrank E L := by
      simpa [E] using Algebra.norm_eq_norm_adjoin ℚ_[2] j
    _ = (5 : ℚ_[2]) ^ Module.finrank E L := by
      rw [norm_adjoin_two_add_primitiveFourthRoot i hi]
    _ = (5 : ℚ_[2]) ^ (2 ^ m) := by rw [hfinRel]


/-- Every element of the `(m+2)`-nd maximal-ideal power of `ℤ₂` is the
`2^m`-fold additive multiple of an element in the square of the maximal
ideal. -/
theorem padicInt_exists_two_power_root_of_mem_maximalIdeal_pow_add_two
    (m : ℕ) (z : ℤ_[2])
    (hz : z ∈ IsLocalRing.maximalIdeal ℤ_[2] ^ (m + 2)) :
    ∃ b : ℤ_[2],
      b ∈ IsLocalRing.maximalIdeal ℤ_[2] ^ 2 ∧
      (2 ^ m) • b = z := by
  rw [PadicInt.maximalIdeal_eq_span_p, Ideal.span_singleton_pow,
    Ideal.mem_span_singleton] at hz
  obtain ⟨c, rfl⟩ := hz
  let b : ℤ_[2] := c * (2 : ℤ_[2]) ^ 2
  refine ⟨b, ?_, ?_⟩
  · rw [PadicInt.maximalIdeal_eq_span_p, Ideal.span_singleton_pow,
      Ideal.mem_span_singleton]
    refine ⟨c, ?_⟩
    simp [b, mul_comm]
  · simp only [nsmul_eq_mul, Nat.cast_pow]
    simp [b, pow_add, mul_comm, mul_left_comm]

/-- Depth two lies in the logarithm/exponential convergence range over
`ℚ₂`. -/
theorem padicDVR_logExp_level_two :
    (LocalFieldTheory.DiscreteValuationField.LocalField.ramificationIndexOfWithZeroValuation
          (LocalFieldTheory.DiscreteValuationField.Examples.Qp.padicDVRValuation 2) : ℚ) /
        (((LocalFieldTheory.DiscreteValuationField.LocalField.ofWithZeroValuation
          (LocalFieldTheory.DiscreteValuationField.Examples.Qp.padicDVRValuation 2)).residueCharacteristic : ℚ) - 1) <
      (2 : ℚ) := by
  let : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  rw [padicDVR_ramificationIndex_eq_one 2,
    padicDVR_residueCharacteristic 2]
  norm_num

/-- Every depth at least two lies in the logarithm/exponential convergence
range over `ℚ₂`. -/
theorem padicDVR_logExp_level_add_two (m : ℕ) :
    (LocalFieldTheory.DiscreteValuationField.LocalField.ramificationIndexOfWithZeroValuation
          (LocalFieldTheory.DiscreteValuationField.Examples.Qp.padicDVRValuation 2) : ℚ) /
        (((LocalFieldTheory.DiscreteValuationField.LocalField.ofWithZeroValuation
          (LocalFieldTheory.DiscreteValuationField.Examples.Qp.padicDVRValuation 2)).residueCharacteristic : ℚ) - 1) <
      ((m + 2 : ℕ) : ℚ) := by
  apply lt_of_lt_of_le padicDVR_logExp_level_two
  exact_mod_cast (Nat.le_add_left 2 m)


/-- Every element of `U^(m+2)` over `ℚ₂` is a `2^m`-th power of an element
of `U²`. -/
theorem padicDVR_higherPrincipalUnit_two_power
    (m : ℕ) :
    let v := LocalFieldTheory.DiscreteValuationField.Examples.Qp.padicDVRValuation 2
    let F :=
      LocalFieldTheory.DiscreteValuationField.MultiplicativeIntegerValuation.completeDVFOfWithZeroValuation v
    ∀ u : LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F (m + 2),
      ∃ r : LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F 2,
        (r : F.valuationSubringˣ) ^ (2 ^ m) =
          (u : F.valuationSubringˣ) := by
  let : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  let v := LocalFieldTheory.DiscreteValuationField.Examples.Qp.padicDVRValuation 2
  let F :=
    LocalFieldTheory.DiscreteValuationField.MultiplicativeIntegerValuation.completeDVFOfWithZeroValuation v
  change ∀ u : LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F (m + 2),
    ∃ r : LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F 2,
      (r : F.valuationSubringˣ) ^ (2 ^ m) =
        (u : F.valuationSubringˣ)
  have hv : Function.Surjective v :=
    (IsDiscreteValuationRing.maximalIdeal ℤ_[2]).valuation_surjective ℚ_[2]
  let E2 := expLogMulEquivOfWithZeroValuation v hv 2
    padicDVR_logExp_level_two
  let En := expLogMulEquivOfWithZeroValuation v hv (m + 2)
    (padicDVR_logExp_level_add_two m)
  let eO : ℤ_[2] ≃+* F.valuationSubring :=
    LocalFieldTheory.DiscreteValuationField.Examples.Qp.padicIntEquivValuationSubring 2
  intro u
  let a : Multiplicative (F.maximalIdeal ^ (m + 2) : Ideal F.valuationSubring) :=
    En.symm u
  let z : ℤ_[2] := eO.symm (a.toAdd : F.valuationSubring)
  have hz : z ∈ IsLocalRing.maximalIdeal ℤ_[2] ^ (m + 2) := by
    apply (ringEquiv_mem_maximalIdeal_pow_iff eO (m + 2) z).1
    simp [z]
  obtain ⟨b, hb, hdb⟩ :=
    padicInt_exists_two_power_root_of_mem_maximalIdeal_pow_add_two m z hz
  have hbO : eO b ∈ F.maximalIdeal ^ 2 := by
    exact (ringEquiv_mem_maximalIdeal_pow_iff eO 2 b).2 hb
  let b2 : (F.maximalIdeal ^ 2 : Ideal F.valuationSubring) :=
    ⟨eO b, hbO⟩
  have hdbO : (2 ^ m) • (eO b) = (a.toAdd : F.valuationSubring) := by
    rw [← map_nsmul eO (2 ^ m) b, hdb]
    simp [z]
  let r : LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F 2 := E2 (Multiplicative.ofAdd b2)
  refine ⟨r, ?_⟩
  have hua : En a = u := En.apply_symm_apply u
  have hrpow :
      r ^ (2 ^ m) =
        E2 ((Multiplicative.ofAdd b2) ^ (2 ^ m)) := by
    change E2 (Multiplicative.ofAdd b2) ^ (2 ^ m) =
      E2 ((Multiplicative.ofAdd b2) ^ (2 ^ m))
    exact (map_pow E2 (Multiplicative.ofAdd b2) (2 ^ m)).symm
  change ((r ^ (2 ^ m) : LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F 2) :
      F.valuationSubringˣ) = (u : F.valuationSubringˣ)
  rw [hrpow, ← hua]
  apply Units.ext
  apply Subtype.ext
  have hleft := expLogMulEquivOfWithZeroValuation_fieldVal v hv 2
    padicDVR_logExp_level_two
    ((Multiplicative.ofAdd b2) ^ (2 ^ m))
  have hright := expLogMulEquivOfWithZeroValuation_fieldVal v hv (m + 2)
    (padicDVR_logExp_level_add_two m) a
  have hleft' :
      ((((E2 ((Multiplicative.ofAdd b2) ^ (2 ^ m)) :
          LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F 2) : F.valuationSubringˣ) :
          F.valuationSubring) : ℚ_[2]) =
        LocalFieldTheory.DiscreteValuationField.MultiplicativeIntegerValuation.expSeriesFieldOfWithZeroValuation
          v ((((Multiplicative.ofAdd b2) ^ (2 ^ m)).toAdd :
            F.valuationSubring) : ℚ_[2])
            (fun q =>
              Nat.cast_ne_zero.mpr (Nat.factorial_ne_zero q)) := by
    exact hleft
  have hright' :
      ((((En a : LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F (m + 2)) : F.valuationSubringˣ) :
          F.valuationSubring) : ℚ_[2]) =
        LocalFieldTheory.DiscreteValuationField.MultiplicativeIntegerValuation.expSeriesFieldOfWithZeroValuation
          v ((a.toAdd : F.valuationSubring) : ℚ_[2])
            (fun q =>
              Nat.cast_ne_zero.mpr (Nat.factorial_ne_zero q)) := by
    exact hright
  rw [hleft', hright']
  congr 2


/-- The unit `5`, regarded as an element of the second higher-principal-unit
group over `ℚ₂`. -/
noncomputable def padicDVR_five :
    letI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
    let F := LocalFieldTheory.DiscreteValuationField.Examples.Qp.padicCompleteDVF 2
    LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F 2 := by
  letI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  let F := LocalFieldTheory.DiscreteValuationField.Examples.Qp.padicCompleteDVF 2
  let eO : ℤ_[2] ≃+* F.valuationSubring :=
    LocalFieldTheory.DiscreteValuationField.Examples.Qp.padicIntEquivValuationSubring 2
  have hfive : IsUnit (5 : ℤ_[2]) := by
    rw [PadicInt.isUnit_iff]
    exact PadicInt.norm_natCast_eq_one_iff.mpr (by norm_num)
  let fiveZ : ℤ_[2]ˣ := hfive.unit
  let fiveO : F.valuationSubringˣ := Units.mapEquiv eO.toMulEquiv fiveZ
  refine ⟨fiveO, ?_⟩
  rw [LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup.mem_iff]
  have hval : (fiveO : F.valuationSubring) = eO (5 : ℤ_[2]) := by
    simp [fiveO, fiveZ]
  rw [hval, ← map_one eO, ← map_sub]
  apply (ringEquiv_mem_maximalIdeal_pow_iff eO 2 ((5 : ℤ_[2]) - 1)).2
  rw [PadicInt.maximalIdeal_eq_span_p, Ideal.span_singleton_pow,
    Ideal.mem_span_singleton]
  refine ⟨1, ?_⟩
  norm_num

/-- The underlying `ℚ₂` value of `padicDVR_five` is `5`. -/
@[simp] theorem padicDVR_five_val :
    letI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
    let F := LocalFieldTheory.DiscreteValuationField.Examples.Qp.padicCompleteDVF 2
    ((((padicDVR_five : LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F 2) :
      F.valuationSubringˣ) : F.valuationSubring) : ℚ_[2]) = 5 := by
  let : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  let F := LocalFieldTheory.DiscreteValuationField.Examples.Qp.padicCompleteDVF 2
  let eO : ℤ_[2] ≃+* F.valuationSubring :=
    LocalFieldTheory.DiscreteValuationField.Examples.Qp.padicIntEquivValuationSubring 2
  change (((Units.mapEquiv eO.toMulEquiv _ : F.valuationSubringˣ) :
    F.valuationSubring) : ℚ_[2]) = 5
  rfl

/-- Every second principal unit over `ℚ₂` lies either in `U³` or in the
coset `5 * U³`. -/
theorem padicDVR_U2_split (u :
    letI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
    let F := LocalFieldTheory.DiscreteValuationField.Examples.Qp.padicCompleteDVF 2
    LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F 2) :
    letI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
    let F := LocalFieldTheory.DiscreteValuationField.Examples.Qp.padicCompleteDVF 2
    (u : F.valuationSubringˣ) ∈ LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F 3 ∨
      (u : F.valuationSubringˣ) /
          (padicDVR_five : LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F 2) ∈
        LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F 3 := by
  let : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  let F := LocalFieldTheory.DiscreteValuationField.Examples.Qp.padicCompleteDVF 2
  let eO : ℤ_[2] ≃+* F.valuationSubring :=
    LocalFieldTheory.DiscreteValuationField.Examples.Qp.padicIntEquivValuationSubring 2
  let x : ℤ_[2] := eO.symm (((u : F.valuationSubringˣ) : F.valuationSubring))
  have hu2 :
      ((u : F.valuationSubringˣ) : F.valuationSubring) - 1 ∈
        F.maximalIdeal ^ 2 :=
    (LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup.mem_iff
      F 2 (u : F.valuationSubringˣ)).1 u.property
  have hx2 : x - 1 ∈ IsLocalRing.maximalIdeal ℤ_[2] ^ 2 := by
    apply (ringEquiv_mem_maximalIdeal_pow_iff eO 2 (x - 1)).1
    rw [map_sub, map_one]
    simpa [x] using hu2
  rw [PadicInt.maximalIdeal_eq_span_p, Ideal.span_singleton_pow,
    Ideal.mem_span_singleton] at hx2
  obtain ⟨c, hc⟩ := hx2
  have hcmod : PadicInt.toZMod c = 0 ∨ PadicInt.toZMod c = 1 := by
    have hlt := ZMod.val_lt (PadicInt.toZMod c)
    have hle : (PadicInt.toZMod c).val ≤ 1 := by omega
    rcases Nat.le_one_iff_eq_zero_or_eq_one.1 hle with h | h
    · left
      calc
        PadicInt.toZMod c = ((PadicInt.toZMod c).val : ZMod 2) :=
          (ZMod.natCast_zmod_val _).symm
        _ = 0 := by rw [h]; norm_num
    · right
      calc
        PadicInt.toZMod c = ((PadicInt.toZMod c).val : ZMod 2) :=
          (ZMod.natCast_zmod_val _).symm
        _ = 1 := by rw [h]; norm_num
  rcases hcmod with hc0 | hc1
  · left
    rw [LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup.mem_iff]
    have hxe : eO x =
        ((u : F.valuationSubringˣ) : F.valuationSubring) := by simp [x]
    rw [← hxe, ← map_one eO, ← map_sub]
    apply (ringEquiv_mem_maximalIdeal_pow_iff eO 3 (x - 1)).2
    rw [PadicInt.maximalIdeal_eq_span_p, Ideal.span_singleton_pow,
      Ideal.mem_span_singleton]
    have hcm : c ∈ IsLocalRing.maximalIdeal ℤ_[2] := by
      rw [← PadicInt.ker_toZMod, RingHom.mem_ker]
      exact hc0
    rw [PadicInt.maximalIdeal_eq_span_p, Ideal.mem_span_singleton] at hcm
    obtain ⟨d, hd⟩ := hcm
    refine ⟨d, ?_⟩
    calc
      x - 1 = (2 : ℤ_[2]) ^ 2 * c := hc
      _ = (2 : ℤ_[2]) ^ 3 * d := by rw [hd]; ring
  · right
    have hcsub : c - 1 ∈ IsLocalRing.maximalIdeal ℤ_[2] := by
      rw [← PadicInt.ker_toZMod, RingHom.mem_ker]
      rw [map_sub, map_one, hc1]
      change (1 : ZMod 2) - 1 = 0
      decide
    rw [PadicInt.maximalIdeal_eq_span_p, Ideal.mem_span_singleton] at hcsub
    obtain ⟨d, hd⟩ := hcsub
    have hx5 : x - 5 ∈ IsLocalRing.maximalIdeal ℤ_[2] ^ 3 := by
      rw [PadicInt.maximalIdeal_eq_span_p, Ideal.span_singleton_pow,
        Ideal.mem_span_singleton]
      refine ⟨d, ?_⟩
      calc
        x - 5 = (x - 1) - 4 := by ring
        _ = (2 : ℤ_[2]) ^ 2 * (c - 1) := by rw [hc]; ring
        _ = (2 : ℤ_[2]) ^ 3 * d := by rw [hd]; ring
    have hdiff :
        ((u : F.valuationSubringˣ) : F.valuationSubring) -
            (((padicDVR_five : LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F 2) :
              F.valuationSubringˣ) : F.valuationSubring) ∈
          F.maximalIdeal ^ 3 := by
      have hxe : eO x =
          ((u : F.valuationSubringˣ) : F.valuationSubring) := by
        simp [x]
      have hefive : eO (5 : ℤ_[2]) =
          (((padicDVR_five :
              LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F 2) :
            F.valuationSubringˣ) : F.valuationSubring) := by
        apply Subtype.ext
        rfl
      have hmapped :=
        (ringEquiv_mem_maximalIdeal_pow_iff eO 3 (x - 5)).2 hx5
      rw [map_sub, hxe, hefive] at hmapped
      exact hmapped
    have hq :
        LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup.quotientUnitHom F 3
            (u : F.valuationSubringˣ) =
          LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup.quotientUnitHom F 3
            ((padicDVR_five : LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F 2) :
              F.valuationSubringˣ) := by
      apply Units.ext
      exact (Ideal.Quotient.mk_eq_mk_iff_sub_mem
        (I := F.maximalIdeal ^ 3)
        (((u : F.valuationSubringˣ) : F.valuationSubring))
        ((((padicDVR_five : LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F 2) :
          F.valuationSubringˣ) : F.valuationSubring))).2 hdiff
    rw [← LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup.quotientUnitHom_ker_eq F 3,
      MonoidHom.mem_ker]
    rw [map_div, hq]
    exact div_self' _

/-- Every second principal unit over `ℚ₂` is either a square in `U²` or five
times such a square. -/
theorem padicDVR_U2_square_class
    (u :
      letI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
      let F := LocalFieldTheory.DiscreteValuationField.Examples.Qp.padicCompleteDVF 2
      LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F 2) :
    letI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
    let F := LocalFieldTheory.DiscreteValuationField.Examples.Qp.padicCompleteDVF 2
    ∃ r : LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F 2,
      (u : F.valuationSubringˣ) = (r : F.valuationSubringˣ) ^ 2 ∨
      (u : F.valuationSubringˣ) =
        (padicDVR_five : LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F 2) *
          (r : F.valuationSubringˣ) ^ 2 := by
  let : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  let F := LocalFieldTheory.DiscreteValuationField.Examples.Qp.padicCompleteDVF 2
  let F' :=
    LocalFieldTheory.DiscreteValuationField.MultiplicativeIntegerValuation.completeDVFOfWithZeroValuation
      (LocalFieldTheory.DiscreteValuationField.Examples.Qp.padicDVRValuation 2)
  have hroot :
      ∀ w : LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F 3,
        ∃ r : LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F 2,
          (r : F.valuationSubringˣ) ^ 2 =
            (w : F.valuationSubringˣ) := by
    change ∀ w :
        LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F' 3,
      ∃ r :
          LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F' 2,
        (r : F'.valuationSubringˣ) ^ 2 = (w : F'.valuationSubringˣ)
    simpa using (padicDVR_higherPrincipalUnit_two_power 1)
  rcases padicDVR_U2_split u with hu | hu
  · let w : LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F 3 := ⟨u, hu⟩
    obtain ⟨r, hr⟩ := hroot w
    exact ⟨r, Or.inl hr.symm⟩
  · let w : LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F 3 :=
      ⟨(u : F.valuationSubringˣ) /
          (padicDVR_five : LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F 2), hu⟩
    obtain ⟨r, hr⟩ := hroot w
    have hr' : (r : F.valuationSubringˣ) ^ 2 =
        (u : F.valuationSubringˣ) /
          (padicDVR_five : LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F 2) := by
      simpa [w] using hr
    refine ⟨r, Or.inr ?_⟩
    calc
      (u : F.valuationSubringˣ) =
          (padicDVR_five : LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F 2) *
            ((u : F.valuationSubringˣ) /
              (padicDVR_five : LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F 2)) := by
                symm
                rw [mul_comm]
                exact div_mul_cancel _ _
      _ = (padicDVR_five : LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F 2) *
            (r : F.valuationSubringˣ) ^ 2 := by rw [← hr']

/-- At the first dyadic cyclotomic level, all first principal units are
norms. -/
theorem fieldPrincipalUnits_le_normSubgroup_cyclotomic_two_zero
    {L : Type} [Field L] [Algebra ℚ_[2] L]
    (zeta : L) (hzeta : IsPrimitiveRoot zeta (2 ^ 1))
    (hgen : Algebra.adjoin ℚ_[2] ({zeta} : Set L) = ⊤) :
    LocalFieldTheory.fieldPrincipalUnits ℚ_[2] 1 ≤ localNormSubgroup ℚ_[2] L := by
  let : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  intro x hx
  have hnorm :=
    LocalFieldTheory.DiscreteValuationField.fieldNormSubgroup_pow_finrank_mem ℚ_[2] L x
  rw [AlgebraicNumberTheory.Valuations.padicCyclotomic_finrank_eq_prime_sub_one_mul_pow
    zeta hzeta hgen] at hnorm
  norm_num at hnorm
  simpa [LocalFieldTheory.DiscreteValuationField.fieldNormSubgroup,
    localNormSubgroup] using hnorm

/-- At a dyadic cyclotomic level `2^(m+2)`, all `(m+2)`-nd principal units
are norms. -/
theorem fieldPrincipalUnits_le_normSubgroup_cyclotomic_two_succ
    (m : ℕ) {L : Type} [Field L] [Algebra ℚ_[2] L]
    (zeta : L) (hzeta : IsPrimitiveRoot zeta (2 ^ (m + 2)))
    (hgen : Algebra.adjoin ℚ_[2] ({zeta} : Set L) = ⊤) :
    LocalFieldTheory.fieldPrincipalUnits ℚ_[2] (m + 2) ≤ localNormSubgroup ℚ_[2] L := by
  let : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  let n := 2 ^ (m + 2)
  let : NeZero n := ⟨pow_ne_zero _ (by norm_num)⟩
  let : IsCyclotomicExtension {n} ℚ_[2] L := by
    simpa [n, Nat.add_assoc] using
      AlgebraicNumberTheory.Valuations.padic_isCyclotomicExtension_of_primitiveRoot_adjoin_eq_top
        (p := 2) (k := m + 1) zeta hzeta hgen
  let : FiniteDimensional ℚ_[2] L :=
    IsCyclotomicExtension.finiteDimensional {n} ℚ_[2] L
  let F := LocalFieldTheory.DiscreteValuationField.Examples.Qp.padicCompleteDVF 2
  let F' :=
    LocalFieldTheory.DiscreteValuationField.MultiplicativeIntegerValuation.completeDVFOfWithZeroValuation
      (LocalFieldTheory.DiscreteValuationField.Examples.Qp.padicDVRValuation 2)
  let eO : 𝒪[ℚ_[2]] ≃+* F.valuationSubring :=
    integerRingEquivPadicDVRValuationSubring 2
  let EU : 𝒪[ℚ_[2]]ˣ ≃* F.valuationSubringˣ :=
    Units.mapEquiv eO.toMulEquiv
  let toField : F.valuationSubringˣ →* ℚ_[2]ˣ :=
    Units.map F.valuation.valuationSubring.subtype.toMonoidHom
  let five : ℚ_[2]ˣ := Units.mk0 (5 : ℚ_[2]) (by norm_num)
  have hfin : Module.finrank ℚ_[2] L = 2 ^ (m + 1) := by
    simpa [Nat.add_assoc] using
      AlgebraicNumberTheory.Valuations.padicCyclotomic_finrank_eq_prime_sub_one_mul_pow
        (p := 2) (k := m + 1) zeta hzeta hgen
  have hnormy :=
    norm_two_add_fourthRoot_cyclotomic_two m zeta hzeta hgen
  have hyne : (2 : L) + zeta ^ (2 ^ m) ≠ 0 := by
    intro hy
    rw [hy, Algebra.norm_zero] at hnormy
    exact (pow_ne_zero (2 ^ m) (by norm_num : (5 : ℚ_[2]) ≠ 0))
      hnormy.symm
  let y : Lˣ := Units.mk0 ((2 : L) + zeta ^ (2 ^ m)) hyne
  have hfiveNorm : five ^ (2 ^ m) ∈ localNormSubgroup ℚ_[2] L := by
    apply MonoidHom.mem_range.mpr
    refine ⟨y, ?_⟩
    apply Units.ext
    change Algebra.norm ℚ_[2] ((2 : L) + zeta ^ (2 ^ m)) =
      (5 : ℚ_[2]) ^ (2 ^ m)
    exact hnormy
  rintro x ⟨u, hu, rfl⟩
  have huD : EU u ∈ LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F (m + 2) := by
    simpa [EU, eO, F] using
      (unitsMapEquiv_mem_higherPrincipalUnitGroup_iff
        2 (m + 2) u).2 hu
  let uD : LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F (m + 2) := ⟨EU u, huD⟩
  have hroot :
      ∀ w : LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F (m + 2),
        ∃ rD : LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F 2,
          (rD : F.valuationSubringˣ) ^ (2 ^ m) =
            (w : F.valuationSubringˣ) := by
    change
      ∀ w :
          LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F' (m + 2),
        ∃ rD :
          LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F' 2,
        (rD : F'.valuationSubringˣ) ^ (2 ^ m) =
          (w : F'.valuationSubringˣ)
    simpa using (padicDVR_higherPrincipalUnit_two_power m)
  obtain ⟨rD, hrD⟩ := hroot uD
  obtain ⟨sD, hsD⟩ :=
    padicDVR_U2_square_class rD
  let s : ℚ_[2]ˣ := toField (sD : F.valuationSubringˣ)
  have hbase :
      toField (uD : F.valuationSubringˣ) =
        integerUnitsToFieldUnits ℚ_[2] u := by
    apply Units.ext
    dsimp [toField, uD, EU, eO]
    exact integerRingEquivPadicDVRValuationSubring_coe
      2 (u : 𝒪[ℚ_[2]])
  have hfive :
      toField
          ((padicDVR_five : LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F 2) :
            F.valuationSubringˣ) = five := by
    apply Units.ext
    dsimp [toField, five, F]
    exact padicDVR_five_val
  have hsNorm : s ^ (2 ^ (m + 1)) ∈ localNormSubgroup ℚ_[2] L := by
    have hsNormRaw :=
      LocalFieldTheory.DiscreteValuationField.fieldNormSubgroup_pow_finrank_mem ℚ_[2] L s
    rw [hfin] at hsNormRaw
    simpa [LocalFieldTheory.DiscreteValuationField.fieldNormSubgroup,
      localNormSubgroup] using hsNormRaw
  rcases hsD with hsD | hsD
  · have huDpow :
        (uD : F.valuationSubringˣ) =
          (sD : F.valuationSubringˣ) ^ (2 ^ (m + 1)) := by
      calc
        (uD : F.valuationSubringˣ) =
            (rD : F.valuationSubringˣ) ^ (2 ^ m) := hrD.symm
        _ = ((sD : F.valuationSubringˣ) ^ 2) ^ (2 ^ m) := by rw [hsD]
        _ = (sD : F.valuationSubringˣ) ^ (2 ^ (m + 1)) := by
          rw [← pow_mul]
          congr 1
          rw [pow_succ]
          ac_rfl
    have hdecomp :
        integerUnitsToFieldUnits ℚ_[2] u = s ^ (2 ^ (m + 1)) := by
      calc
        integerUnitsToFieldUnits ℚ_[2] u =
            toField (uD : F.valuationSubringˣ) := hbase.symm
        _ = toField ((sD : F.valuationSubringˣ) ^ (2 ^ (m + 1))) :=
          congrArg toField huDpow
        _ = s ^ (2 ^ (m + 1)) := by
          exact map_pow toField (sD : F.valuationSubringˣ) (2 ^ (m + 1))
    rw [hdecomp]
    exact hsNorm
  · have huDprod :
        (uD : F.valuationSubringˣ) =
          ((padicDVR_five : LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F 2) :
              F.valuationSubringˣ) ^ (2 ^ m) *
            (sD : F.valuationSubringˣ) ^ (2 ^ (m + 1)) := by
      calc
        (uD : F.valuationSubringˣ) =
            (rD : F.valuationSubringˣ) ^ (2 ^ m) := hrD.symm
        _ = (((padicDVR_five : LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F 2) :
                F.valuationSubringˣ) *
              (sD : F.valuationSubringˣ) ^ 2) ^ (2 ^ m) := by rw [hsD]
        _ = ((padicDVR_five : LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F 2) :
                F.valuationSubringˣ) ^ (2 ^ m) *
              ((sD : F.valuationSubringˣ) ^ 2) ^ (2 ^ m) := by
            rw [mul_pow]
        _ = ((padicDVR_five : LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F 2) :
                F.valuationSubringˣ) ^ (2 ^ m) *
              (sD : F.valuationSubringˣ) ^ (2 ^ (m + 1)) := by
            rw [← pow_mul]
            congr 2
            rw [pow_succ]
            ac_rfl
    have hdecomp :
        integerUnitsToFieldUnits ℚ_[2] u =
          five ^ (2 ^ m) * s ^ (2 ^ (m + 1)) := by
      calc
        integerUnitsToFieldUnits ℚ_[2] u =
            toField (uD : F.valuationSubringˣ) := hbase.symm
        _ = toField
            (((padicDVR_five : LocalFieldTheory.DiscreteValuationField.CompleteDVF.higherPrincipalUnitGroup F 2) :
                  F.valuationSubringˣ) ^ (2 ^ m) *
              (sD : F.valuationSubringˣ) ^ (2 ^ (m + 1))) :=
          congrArg toField huDprod
        _ = five ^ (2 ^ m) * s ^ (2 ^ (m + 1)) := by
          rw [map_mul, map_pow, map_pow, hfive]
    rw [hdecomp]
    exact (localNormSubgroup ℚ_[2] L).mul_mem hfiveNorm hsNorm

/-- At every positive dyadic cyclotomic level, the principal units at the
corresponding depth are norms. -/
theorem fieldPrincipalUnits_le_normSubgroup_cyclotomic_two
    (k : ℕ) {L : Type} [Field L] [Algebra ℚ_[2] L]
    (zeta : L) (hzeta : IsPrimitiveRoot zeta (2 ^ (k + 1)))
    (hgen : Algebra.adjoin ℚ_[2] ({zeta} : Set L) = ⊤) :
    LocalFieldTheory.fieldPrincipalUnits ℚ_[2] (k + 1) ≤ localNormSubgroup ℚ_[2] L := by
  cases k with
  | zero =>
      simpa using
        fieldPrincipalUnits_le_normSubgroup_cyclotomic_two_zero
          zeta hzeta hgen
  | succ m =>
      simpa [Nat.add_assoc] using
        fieldPrincipalUnits_le_normSubgroup_cyclotomic_two_succ
          m zeta hzeta hgen


/-- Over `ℚ₂`, the standard subgroup generated by `2` and `U^(k+1)` is
contained in the corresponding cyclotomic norm subgroup. -/
theorem uniformizerPrincipalSubgroup_le_normSubgroup_cyclotomic_two
    (k : ℕ) {L : Type} [Field L] [Algebra ℚ_[2] L]
    (zeta : L) (hzeta : IsPrimitiveRoot zeta (2 ^ (k + 1)))
    (hgen : Algebra.adjoin ℚ_[2] ({zeta} : Set L) = ⊤) :
    LocalFieldTheory.uniformizerPrincipalSubgroup ℚ_[2] (padicPrimeUnit 2) 1 (k + 1) ≤
      localNormSubgroup ℚ_[2] L := by
  let : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  rw [LocalFieldTheory.uniformizerPrincipalSubgroup]
  apply sup_le
  · rw [Subgroup.zpowers_le]
    simpa using
      padicPrimeUnit_mem_normSubgroup_cyclotomic
        2 zeta hzeta hgen
  · exact fieldPrincipalUnits_le_normSubgroup_cyclotomic_two
      k zeta hzeta hgen

/-- Over `ℚ₂`, the norm subgroup of a primitive `2^(k+1)`-st cyclotomic
extension is exactly the subgroup generated by `2` and `U^(k+1)`. -/
theorem localNormSubgroup_eq_uniformizerPrincipalSubgroup_cyclotomicPrimePower_two
    {k : ℕ} {L : Type} [Field L] [Algebra ℚ_[2] L]
    (zeta : L) (hzeta : IsPrimitiveRoot zeta (2 ^ (k + 1)))
    (hgen : Algebra.adjoin ℚ_[2] ({zeta} : Set L) = ⊤) :
    localNormSubgroup ℚ_[2] L =
      LocalFieldTheory.uniformizerPrincipalSubgroup ℚ_[2]
        (padicPrimeUnit 2) 1 (k + 1) := by
  let : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  let : IsNonarchimedeanLocalField ℚ_[2] :=
    padicIsNonarchimedeanLocalField 2
  let n := 2 ^ (k + 1)
  let : NeZero n := ⟨pow_ne_zero _ (by norm_num)⟩
  let : IsCyclotomicExtension {n} ℚ_[2] L := by
    simpa [n] using
      AlgebraicNumberTheory.Valuations.padic_isCyclotomicExtension_of_primitiveRoot_adjoin_eq_top
        zeta hzeta hgen
  let : FiniteDimensional ℚ_[2] L :=
    IsCyclotomicExtension.finiteDimensional {n} ℚ_[2] L
  let : IsAbelianGalois ℚ_[2] L :=
    IsCyclotomicExtension.isAbelianGalois {n} ℚ_[2] L
  let H :=
    LocalFieldTheory.uniformizerPrincipalSubgroup ℚ_[2]
      (padicPrimeUnit 2) 1 (k + 1)
  let N := localNormSubgroup ℚ_[2] L
  have hHinv : H =
      LocalFieldTheory.uniformizerPrincipalSubgroup ℚ_[2]
        (padicPrimeUnit 2)⁻¹ 1 (k + 1) := by
    simp [H, LocalFieldTheory.uniformizerPrincipalSubgroup, Subgroup.zpowers_inv]
  have hcardH : Nat.card (ℚ_[2]ˣ ⧸ H) = (2 - 1) * 2 ^ k := by
    rw [hHinv]
    exact nat_card_fieldUnitsUniformizerPrincipalQuot_padic_succ 2 k
  have hindexH : H.index = (2 - 1) * 2 ^ k := by
    rw [Subgroup.index_eq_card]
    exact hcardH
  have hcardN : Nat.card (NormQuotient ℚ_[2] L) = (2 - 1) * 2 ^ k := by
    calc
      Nat.card (NormQuotient ℚ_[2] L) = Module.finrank ℚ_[2] L := by
        exact card_normQuotient_eq_finrank_of_isAbelianGalois ℚ_[2] L
      _ = (2 - 1) * 2 ^ k :=
        AlgebraicNumberTheory.Valuations.padicCyclotomic_finrank_eq_prime_sub_one_mul_pow
          zeta hzeta hgen
  have hindexN : N.index = (2 - 1) * 2 ^ k := by
    rw [Subgroup.index_eq_card]
    exact hcardN
  have hdpos : 0 < (2 - 1) * 2 ^ k := by positivity
  let : H.FiniteIndex := ⟨by
    rw [hindexH]
    exact Nat.ne_of_gt hdpos⟩
  have hHN : H ≤ N := by
    exact uniformizerPrincipalSubgroup_le_normSubgroup_cyclotomic_two
      k zeta hzeta hgen
  apply Eq.symm
  apply le_antisymm hHN
  by_contra hNH
  have hne : H ≠ N := by
    intro heq
    apply hNH
    rw [heq]
  have hstrict : H < N := lt_of_le_of_ne hHN hne
  have hi := Subgroup.index_strictAnti hstrict
  rw [hindexH, hindexN] at hi
  exact (Nat.lt_irrefl _ hi)

/-- For every prime `p`, the norm subgroup of a primitive `p^(k+1)`-st
cyclotomic extension is exactly the subgroup generated by `p` and
`U^(k+1)`. -/
theorem localNormSubgroup_eq_uniformizerPrincipalSubgroup_cyclotomicPrimePower
    {k : ℕ} {L : Type} [Field L] [Algebra ℚ_[p] L]
    (zeta : L) (hzeta : IsPrimitiveRoot zeta (p ^ (k + 1)))
    (hgen : Algebra.adjoin ℚ_[p] ({zeta} : Set L) = ⊤) :
    localNormSubgroup ℚ_[p] L =
      LocalFieldTheory.uniformizerPrincipalSubgroup ℚ_[p]
        (padicPrimeUnit p) 1 (k + 1) := by
  by_cases hp2 : p = 2
  · subst p
    exact
      localNormSubgroup_eq_uniformizerPrincipalSubgroup_cyclotomicPrimePower_two
        zeta hzeta hgen
  · exact
      localNormSubgroup_eq_uniformizerPrincipalSubgroup_cyclotomicPrimePower_odd
        p hp2 zeta hzeta hgen

end LocalClassFieldTheory

end
