/-
Copyright (c) 2026 Naganori Yamaguchi (https://github.com/n-yamaguchi-0729). All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Naganori Yamaguchi (assisted by OpenAI Codex)
-/

import ClassFieldTheory.LocalFieldTheory.Padic.Cyclotomic.Unramified.CanonicalExtension
import ValuedFieldTheory.LocalField.Padic.PrincipalUnits
import ValuedFieldTheory.LocalField.NonarchimedeanLocalField.ValuedTopology
import ClassFieldTheory.LocalClassFieldTheory.Finite.Unramified.PrincipalUnits.NormSide
import ClassFieldTheory.LocalClassFieldTheory.Finite.Unramified.PrincipalUnits.Basic
import ClassFieldTheory.LocalClassFieldTheory.Finite.Unramified.PrincipalUnits.Trace
import ClassFieldTheory.LocalClassFieldTheory.Finite.Unramified.PrincipalUnits.Lift
import ClassFieldTheory.LocalClassFieldTheory.Finite.Unramified.ResidueNorm
import ClassFieldTheory.LocalClassFieldTheory.Finite.Unramified.Norm
import ClassFieldTheory.LocalClassFieldTheory.Finite.Unramified.Uniformizer
import ClassFieldTheory.LocalClassFieldTheory.Finite.Unramified.Cohomology
import ClassFieldTheory.LocalClassFieldTheory.Finite.LocalReciprocity.UnramifiedNormComparison
import ValuedFieldTheory.Valuation.LocalRingEquiv

set_option autoImplicit false

/-!
# The unramified cyclotomic norm subgroup over `ℚ_p`

This file joins the canonical-valuation form of the unramified cyclotomic theorem to the
unramified norm computation. For a field generated by a
primitive root of order `p ^ f - 1`, that theorem supplies the
unramified extension of degree `f`; the result below expresses its norm
subgroup in the spectral-norm presentation used by local class field theory.
-/

noncomputable section

namespace LocalClassFieldTheory

open LocalFieldTheory.Padic
open ValuationTheory

open scoped NNReal ValuativeRel

/-- Let `L/ℚ_p` be generated by a primitive root of order `p ^ f - 1`.
The unramified cyclotomic theorem identifies `L` with the unramified extension of degree
`f`; consequently its norm subgroup is `⟨p ^ f⟩ × U¹`.

The proof compares the complete-DVF valuation with the spectral valuation
used by the unramified norm theorem.  Uniqueness of the
extended valuation on the finite separable extension transports
ramification index one between the two presentations. -/
theorem normSubgroup_eq_unramifiedNormSubgroup_padic_prime_pow_sub_one
    (p f : ℕ) [Fact p.Prime] (hf : 0 < f)
    (L : Type) [Field L] [Algebra ℚ_[p] L]
    [FiniteDimensional ℚ_[p] L] [IsGalois ℚ_[p] L]
    [IsNonarchimedeanLocalField ℚ_[p]]
    {ζ : L} (hζ : IsPrimitiveRoot ζ (p ^ f - 1))
    (hζgen : Algebra.adjoin ℚ_[p] ({ζ} : Set L) = ⊤) :
    LocalFieldTheory.localNormSubgroup ℚ_[p] L = unramifiedNormSubgroup ℚ_[p] f := by
  let : NontriviallyNormedField L :=
    spectralNorm.nontriviallyNormedField ℚ_[p] L
  let : NormedSpace ℚ_[p] L := spectralNorm.normedSpace ℚ_[p] L
  let : CompleteSpace L := spectralNorm.completeSpace ℚ_[p] L
  let : LocallyCompactSpace L :=
    LocallyCompactSpace.of_finiteDimensional_of_complete ℚ_[p] L
  let : IsUltrametricDist L :=
    ⟨fun x y z => by
      change ‖x - z‖ ≤ max ‖x - y‖ ‖y - z‖
      rw [← sub_add_sub_cancel x y z]
      exact isNonarchimedean_spectralNorm
        (K := ℚ_[p]) (L := L) (x - y) (y - z)⟩
  let : Valued L ℝ≥0 := NormedField.toValued
  let vL : Valuation L ℝ≥0 := Valued.v
  let : vL.IsNontrivial :=
    (inferInstance : (NormedField.valuation (K := L)).IsNontrivial)
  let : ValuativeRel L := ValuativeRel.ofValuation vL
  let : vL.Compatible := Valuation.Compatible.ofValuation vL
  let : ValuativeRel.IsNontrivial L :=
    (ValuativeRel.isNontrivial_iff_isNontrivial vL).2 inferInstance
  let : IsValuativeTopology L :=
    LocalFieldTheory.isValuativeTopology_of_valued_ofValuation L ℝ≥0
  let : IsNonarchimedeanLocalField L :=
    { toIsValuativeTopology := inferInstance
      toLocallyCompactSpace := inferInstance
      toIsNontrivial := inferInstance }

  let : (ValuativeRel.valuation ℚ_[p]).HasExtension
      (ValuativeRel.valuation L) := by
    apply Valuation.HasExtension.ofComapInteger
    ext x
    change ValuativeRel.valuation L (algebraMap ℚ_[p] L x) ≤ 1 ↔
      ValuativeRel.valuation ℚ_[p] x ≤ 1
    rw [← (ValuativeRel.valuation L).vle_one_iff, vL.vle_one_iff]
    change spectralNorm ℚ_[p] L (algebraMap ℚ_[p] L x) ≤ 1 ↔
      ValuativeRel.valuation ℚ_[p] x ≤ 1
    rw [spectralNorm_extends]
    rw [← integer_mem_iff_norm_le_one p x,
      Valuation.mem_integer_iff]

  let base := LocalFieldTheory.DiscreteValuationField.Examples.Qp.padicCompleteDVF p
  let : base.valuation.HasExtension vL := by
    apply Valuation.HasExtension.ofComapInteger
    ext x
    change vL (algebraMap ℚ_[p] L x) ≤ 1 ↔ base.valuation x ≤ 1
    change spectralNorm ℚ_[p] L (algebraMap ℚ_[p] L x) ≤ 1 ↔
      x ∈ base.valuation.valuationSubring
    rw [spectralNorm_extends]
    constructor
    · intro hx
      let u : 𝒪[ℚ_[p]] :=
        ⟨x, (integer_mem_iff_norm_le_one p x).2 hx⟩
      exact (integerRingEquivPadicDVRValuationSubring p u).property
    · intro hx
      let y : base.valuationSubring := ⟨x, hx⟩
      let u : 𝒪[ℚ_[p]] :=
        (integerRingEquivPadicDVRValuationSubring p).symm y
      have hu : (u : ℚ_[p]) = x := by
        calc
          (u : ℚ_[p]) =
              ((integerRingEquivPadicDVRValuationSubring p u :
                base.valuationSubring) : ℚ_[p]) := by rfl
          _ = (y : ℚ_[p]) := congrArg Subtype.val
            ((integerRingEquivPadicDVRValuationSubring p).apply_symm_apply y)
          _ = x := rfl
      have humem :
          (u : ℚ_[p]) ∈ (ValuativeRel.valuation ℚ_[p]).integer := u.property
      have hunorm :=
        (integer_mem_iff_norm_le_one p (u : ℚ_[p])).1 humem
      simpa [hu] using hunorm

  let : Algebra.IsIntegral 𝒪[ℚ_[p]] 𝒪[L] := ⟨by
    intro y
    apply IsIntegral.tower_bot
      (R := 𝒪[ℚ_[p]]) (A := 𝒪[L]) (B := L)
      (Subring.subtype_injective (ValuativeRel.valuation L).integer)
    have hyv : vL (y : L) ≤ 1 := by
      apply (vL.vle_one_iff).1
      apply ((ValuativeRel.valuation L).vle_one_iff).2
      exact y.property
    have hynorm : ‖(y : L)‖ ≤ 1 := by
      have hynormNN : ‖(y : L)‖₊ ≤ 1 := by
        simpa [vL, NormedField.valuation_apply] using hyv
      exact_mod_cast hynormNN
    change spectralNorm ℚ_[p] L (y : L) ≤ 1 at hynorm
    have hcoeffNorm :
        ∀ n : ℕ, ‖(minpoly ℚ_[p] (y : L)).coeff n‖ ≤ 1 :=
      (spectralValue_le_one_iff
        (minpoly.monic (Algebra.IsIntegral.isIntegral (y : L)))).1
        (by simpa [spectralNorm] using hynorm)
    have hcoeff :
        (↑(minpoly ℚ_[p] (y : L)).coeffs : Set ℚ_[p]) ⊆
          (ValuativeRel.valuation ℚ_[p]).integer := by
      intro c hc
      obtain ⟨n, _hn, rfl⟩ := Polynomial.mem_coeffs_iff.mp hc
      exact (integer_mem_iff_norm_le_one p _).2 (hcoeffNorm n)
    let q : Polynomial 𝒪[ℚ_[p]] :=
      (minpoly ℚ_[p] (y : L)).toSubring
        (ValuativeRel.valuation ℚ_[p]).integer hcoeff
    refine ⟨q, ?_, ?_⟩
    · exact (Polynomial.monic_toSubring
        (minpoly ℚ_[p] (y : L))
        (ValuativeRel.valuation ℚ_[p]).integer hcoeff).2
          (minpoly.monic (Algebra.IsIntegral.isIntegral (y : L)))
    · have hmaproot :
          Polynomial.aeval (y : L)
            (q.map (algebraMap 𝒪[ℚ_[p]] ℚ_[p])) = 0 := by
        dsimp only [q]
        rw [show algebraMap 𝒪[ℚ_[p]] ℚ_[p] =
          (ValuativeRel.valuation ℚ_[p]).integer.subtype from rfl,
          Polynomial.map_toSubring]
        exact minpoly.aeval ℚ_[p] (y : L)
      rwa [Polynomial.aeval_map_algebraMap ℚ_[p] (y : L) q] at hmaproot⟩

  let : Algebra.IsIntegral
      (ValuativeRel.valuation ℚ_[p]).valuationSubring
      (ValuativeRel.valuation L).valuationSubring := by
    change Algebra.IsIntegral 𝒪[ℚ_[p]] 𝒪[L]
    infer_instance
  let hIntegralClosure : IsIntegralClosure 𝒪[L] 𝒪[ℚ_[p]] L :=
    ValuationTheory.DiscreteValuationField.Valuation.valuationSubring_isIntegralClosure_of_isIntegral
      (ValuativeRel.valuation ℚ_[p]) (ValuativeRel.valuation L)
  let : IsIntegralClosure 𝒪[L] 𝒪[ℚ_[p]] L := hIntegralClosure
  let : Module.Finite 𝒪[ℚ_[p]] 𝒪[L] :=
    LocalFieldTheory.integerRing_moduleFinite_of_isIntegralClosure ℚ_[p] L

  obtain ⟨target, hExt, hTarget, _hUnram, _hdegree⟩ :=
    AlgebraicNumberTheory.Valuations.exists_padicCyclotomic_completeDVF_isFiniteUnramified_degree_eq
      p f hf hζ hζgen
  let : base.valuation.HasExtension target.valuation := hExt
  let : IsIntegralClosure target.valuationSubring base.valuationSubring L := hTarget
  let : base.valuation.HasExtension vL.valuationSubring.valuation := by
    apply
      ValuationTheory.DiscreteValuationField.Valuation.hasExtension_valuation_of_valuationSubring_pullback
    intro x
    change vL (algebraMap ℚ_[p] L x) ≤ 1 ↔ base.valuation x ≤ 1
    exact _root_.Valuation.HasExtension.val_map_le_one_iff base.valuation vL x
  have hTargetEq : target.valuation.valuationSubring = vL.valuationSubring :=
    ValuationTheory.DiscreteValuationField.ValuedExtension.target_valuationSubring_eq_of_finite_separable
        (base := base) (target := target) vL.valuationSubring
  let eBase : 𝒪[ℚ_[p]] ≃+* base.valuationSubring :=
    integerRingEquivPadicDVRValuationSubring p
  let eTarget : target.valuationSubring ≃+* 𝒪[L] :=
    { toFun := fun x => ⟨x, by
          change ValuativeRel.valuation L (x : L) ≤ 1
          apply ((ValuativeRel.valuation L).vle_one_iff).1
          apply (vL.vle_one_iff).2
          change (x : L) ∈ vL.valuationSubring
          rw [← hTargetEq]
          exact x.property⟩
      invFun := fun x => ⟨x, by
          change target.valuation (x : L) ≤ 1
          change (x : L) ∈ target.valuation.valuationSubring
          rw [hTargetEq]
          apply (vL.vle_one_iff).1
          apply ((ValuativeRel.valuation L).vle_one_iff).2
          exact x.property⟩
      left_inv := fun x => Subtype.ext rfl
      right_inv := fun x => Subtype.ext rfl
      map_mul' := fun _ _ => Subtype.ext rfl
      map_add' := fun _ _ => Subtype.ext rfl }
  let iCanonical : base.valuationSubring →+* target.valuationSubring :=
    algebraMap base.valuationSubring target.valuationSubring
  let iLocal : 𝒪[ℚ_[p]] →+* 𝒪[L] := algebraMap 𝒪[ℚ_[p]] 𝒪[L]
  let : IsDiscreteValuationRing base.valuationSubring :=
    base.valuationSubring_isDiscreteValuationRing
  let : IsDiscreteValuationRing target.valuationSubring :=
    target.valuationSubring_isDiscreteValuationRing
  have hramCanonical :
      Ideal.ramificationIdx'
        (IsLocalRing.maximalIdeal base.valuationSubring)
        (IsLocalRing.maximalIdeal target.valuationSubring) = 1 := by
    have h :=
      AlgebraicNumberTheory.Valuations.padicCyclotomic_ramificationIndex_eq_one_prime_pow_sub_one
        p f hf hζ hζgen target
    change Ideal.ramificationIdx'
      (IsLocalRing.maximalIdeal base.valuationSubring)
      (IsLocalRing.maximalIdeal target.valuationSubring) = 1 at h
    exact h
  have hiCanonical : Function.Injective iCanonical := by
    intro x y hxy
    apply Subtype.ext
    exact (algebraMap ℚ_[p] L).injective (congrArg Subtype.val hxy)
  have hiCanonicalAlg :
      Function.Injective
        (algebraMap base.valuationSubring target.valuationSubring) := by
    simpa only [iCanonical] using hiCanonical
  have hmapCanonical :
      Ideal.map iCanonical (IsLocalRing.maximalIdeal base.valuationSubring) =
        IsLocalRing.maximalIdeal target.valuationSubring := by
    have hmap :
        Ideal.map (algebraMap base.valuationSubring target.valuationSubring)
            (IsLocalRing.maximalIdeal base.valuationSubring) =
          IsLocalRing.maximalIdeal target.valuationSubring ^
            Ideal.ramificationIdx'
              (IsLocalRing.maximalIdeal base.valuationSubring)
              (IsLocalRing.maximalIdeal target.valuationSubring) := by
      exact map_maximalIdeal_eq_pow_ramificationIdx hiCanonicalAlg
    rw [hramCanonical, pow_one] at hmap
    simpa only [iCanonical] using hmap
  have hmapBase :
      Ideal.map eBase (IsLocalRing.maximalIdeal 𝒪[ℚ_[p]]) =
        IsLocalRing.maximalIdeal base.valuationSubring :=
    ringEquiv_map_maximalIdeal eBase
  have hmapTarget :
      Ideal.map eTarget (IsLocalRing.maximalIdeal target.valuationSubring) =
        IsLocalRing.maximalIdeal 𝒪[L] :=
    ringEquiv_map_maximalIdeal eTarget
  have hcommute :
      eTarget.toRingHom.comp (iCanonical.comp eBase.toRingHom) = iLocal := by
    ext x
    rfl
  have hmapLocal :
      Ideal.map iLocal (IsLocalRing.maximalIdeal 𝒪[ℚ_[p]]) =
        IsLocalRing.maximalIdeal 𝒪[L] := by
    calc
      Ideal.map iLocal (IsLocalRing.maximalIdeal 𝒪[ℚ_[p]]) =
          Ideal.map (eTarget.toRingHom.comp (iCanonical.comp eBase.toRingHom))
            (IsLocalRing.maximalIdeal 𝒪[ℚ_[p]]) := by rw [hcommute]
      _ = Ideal.map eTarget
          (Ideal.map (iCanonical.comp eBase.toRingHom)
            (IsLocalRing.maximalIdeal 𝒪[ℚ_[p]])) :=
        (Ideal.map_map (iCanonical.comp eBase.toRingHom) eTarget.toRingHom).symm
      _ = Ideal.map eTarget
          (Ideal.map iCanonical
            (Ideal.map eBase (IsLocalRing.maximalIdeal 𝒪[ℚ_[p]]))) := by
        congr 1
        exact (Ideal.map_map eBase.toRingHom iCanonical).symm
      _ = IsLocalRing.maximalIdeal 𝒪[L] := by
        rw [hmapBase, hmapCanonical, hmapTarget]
  have hmapLocalAlg :
      Ideal.map (algebraMap 𝒪[ℚ_[p]] 𝒪[L])
          (IsLocalRing.maximalIdeal 𝒪[ℚ_[p]]) =
        IsLocalRing.maximalIdeal 𝒪[L] := by
    simpa only [iLocal] using hmapLocal
  let : LocalFieldTheory.IsNonarchimedeanLocalField.IsUnramifiedValuedExtension
      ℚ_[p] L := ⟨by
    have hp : (IsLocalRing.maximalIdeal 𝒪[ℚ_[p]]) ≠ ⊥ :=
      IsDiscreteValuationRing.not_a_field 𝒪[ℚ_[p]]
    rw [← Ideal.ramificationIdx'_eq_ramificationIdx
      (IsLocalRing.maximalIdeal 𝒪[ℚ_[p]])
      (IsLocalRing.maximalIdeal 𝒪[L]) hp]
    apply Ideal.ramificationIdx'_spec
    · rw [hmapLocalAlg, pow_one]
    · rw [hmapLocalAlg]
      simpa using not_le_of_gt (Ideal.pow_succ_lt_pow
        (IsDiscreteValuationRing.not_a_field 𝒪[L]) 1)⟩
  calc
    LocalFieldTheory.localNormSubgroup ℚ_[p] L =
        unramifiedNormSubgroup ℚ_[p] (Module.finrank ℚ_[p] L) :=
      normSubgroup_eq_unramifiedNormSubgroup_of_isIntegralClosure ℚ_[p] L
    _ = unramifiedNormSubgroup ℚ_[p] f := by
      rw [AlgebraicNumberTheory.Valuations.padicCyclotomic_finrank_prime_pow_sub_one
        p f hf hζ hζgen]

end LocalClassFieldTheory

end
