name = "FiniteAbelianLocalReciprocityv2"
version = "0.1.0"
defaultTargets = ["ClassFieldTheory.All", "Challenge", "Solution"]

enableArtifactCache = false
restoreAllArtifacts = false

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "065356127b1dc0016f66b7283ce0ce2c4055aa55"

[[lean_lib]]
name = "ClassFieldTheory.All"
srcDir = "Lean4"
globs = ["ClassFieldTheory.+"]
leanOptions = {linter.missingDocs = true}

[[lean_lib]]
name = "ValuedFieldTheory"
srcDir = "Lean4"
globs = ["ValuedFieldTheory.+"]

[[lean_lib]]
name = "GaloisCohomology"
srcDir = "Lean4"
globs = ["GaloisCohomology.+"]

[[lean_lib]]
name = "ProCGroups"
srcDir = "Lean4"
globs = ["ProCGroups.+"]

[[lean_lib]]
name = "Challenge"
roots = ["Challenge"]

[[lean_lib]]
name = "Solution"
roots = ["Solution"]
