/-
Copyright (c) 2026 Naganori Yamaguchi (https://github.com/n-yamaguchi-0729). All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Naganori Yamaguchi (assisted by OpenAI Codex)
-/

import ClassFieldTheory.AlgebraicNumberTheory.NumberField.CompletelySplitPrimes
import ClassFieldTheory.AlgebraicNumberTheory.NumberField.CompletelySplitPrimesModFour
import ClassFieldTheory.AlgebraicNumberTheory.NumberField.DegreeOnePrimes
import ClassFieldTheory.AlgebraicNumberTheory.NumberField.IntegralPrimitiveElement
import ClassFieldTheory.AlgebraicNumberTheory.NumberField.PlaceEquiv
import ClassFieldTheory.AlgebraicNumberTheory.NumberField.SchurPrimeDivisors
import ClassFieldTheory.AlgebraicNumberTheory.NumberField.EverywhereUnramifiedTower
import ClassFieldTheory.AlgebraicNumberTheory.NumberField.FiniteUnramifiedEtaleBridge
import ClassFieldTheory.AlgebraicNumberTheory.NumberField.FiniteUnramifiedTower
import ClassFieldTheory.AlgebraicNumberTheory.NumberField.MathlibUnramifiedInterface
import ClassFieldTheory.AlgebraicNumberTheory.NumberField.CompletelySplitFinset
import ClassFieldTheory.AlgebraicNumberTheory.NumberField.GaloisDifferentBound
import ClassFieldTheory.AlgebraicNumberTheory.NumberField.RootDiscriminantBound
import ClassFieldTheory.AlgebraicNumberTheory.NumberField.SmallModel
import ClassFieldTheory.AlgebraicNumberTheory.NumberField.SupportedDiscriminantBound
import ClassFieldTheory.AlgebraicNumberTheory.NumberField.TameDifferentTrace

set_option autoImplicit false

/-! # Finite and everywhere-unramified towers of number fields -/
