/-
Copyright (c) 2026 Naganori Yamaguchi (https://github.com/n-yamaguchi-0729). All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Naganori Yamaguchi (assisted by OpenAI Codex)
-/

import ClassFieldTheory.GlobalClassFieldTheory.Reciprocity.FinitePlaceArtin.Conjugation
import ClassFieldTheory.LocalClassFieldTheory.Kummer.LocalHilbertSymbol
import Mathlib.FieldTheory.KummerExtension

set_option autoImplicit false

/-!
# Global-place Hilbert symbols

This module starts the local-to-global Hilbert-symbol layer.  At a finite
place, global units are mapped into the canonical absolute-value completion,
the genuine local Hilbert symbol is evaluated there, and its value is
transported back to the roots of unity in the number field.

The later local--global comparison can therefore identify this intrinsically
local definition with the root character of the finite-place global Artin
automorphism without building that comparison into the definition.
-/

open scoped Classical NumberField
open NumberField IsDedekindDomain

noncomputable section

namespace GlobalClassFieldTheory
namespace Reciprocity

open KummerTheory
open AlgebraicNumberTheory.Valuations

variable (K : Type) [Field K] [NumberField K]

omit [NumberField K] in
/-- A Kummer root quotient does not depend on the chosen `n`-th root once
the base field contains a primitive `n`-th root of unity.  This is the
root-choice transport leaf used by the finite-place local--global
comparison. -/
theorem rootQuotient_eq_of_same_pow_of_primitiveRoots
    {L : Type} [Field L] [Algebra K L]
    (n : ℕ+) (hmu : (primitiveRoots (n : ℕ) K).Nonempty)
    (a : Kˣ) (u u' : Lˣ)
    (hu : u ^ (n : ℕ) =
      Units.map (algebraMap K L).toMonoidHom a)
    (hu' : u' ^ (n : ℕ) =
      Units.map (algebraMap K L).toMonoidHom a)
    (sigma : Gal(L/K)) :
    rootQuotient (K := K) (L := L) u sigma =
      rootQuotient (K := K) (L := L) u' sigma := by
  let D := chosenFiniteKummerRadicalDatum (K := K) (L := L) n
  let delta : D.carrier := ⟨a, u, hu⟩
  let hfixed :=
    nthRootsOfUnity_fixed (K := K) (L := L) n
      (nthRootsOfUnityInBase_of_primitiveRoots
        (K := K) (L := L) n hmu)
  calc
    rootQuotient (K := K) (L := L) u sigma =
        D.rootCharacter delta hfixed sigma :=
      D.rootCharacter_eq_of_same_pow hfixed delta hu sigma
    _ = rootQuotient (K := K) (L := L) u' sigma :=
      (D.rootCharacter_eq_of_same_pow hfixed delta hu' sigma).symm

omit [NumberField K] in
/-- Conjugating a Galois automorphism through an algebra equivalence carries
the corresponding root quotient through the same equivalence. -/
theorem rootQuotient_map_algEquiv
    {L E : Type} [Field L] [Field E] [Algebra K L] [Algebra K E]
    (e : L ≃ₐ[K] E) (u : Lˣ) (sigma : Gal(L/K)) :
    rootQuotient (K := K) (L := E)
        (Units.map e.toMonoidHom u) (AlgEquiv.autCongr e sigma) =
      Units.map e.toMonoidHom
        (rootQuotient (K := K) (L := L) u sigma) := by
  apply Units.ext
  simp [rootQuotient, AlgEquiv.autCongr_apply]

/-- A field generated by one `n`-th root is the splitting field of its
Kummer polynomial as soon as the base field already contains a primitive
`n`-th root of unity. -/
theorem isSplittingField_X_pow_sub_C_of_root_adjoin_eq_top_of_primitiveRoots
    (F E : Type) [Field F] [Field E] [Algebra F E]
    [FiniteDimensional F E]
    (n : ℕ+) (hmu : (primitiveRoots (n : ℕ) F).Nonempty)
    (a : F) (alpha : E)
    (halpha : alpha ^ (n : ℕ) = algebraMap F E a)
    (hgenerate : IntermediateField.adjoin F {alpha} = ⊤) :
    Polynomial.IsSplittingField F E
      (Polynomial.X ^ (n : ℕ) - Polynomial.C a) := by
  constructor
  · rw [Polynomial.map_sub, Polynomial.map_pow, Polynomial.map_C,
      Polynomial.map_X]
    obtain ⟨zeta, hzeta⟩ := hmu
    exact X_pow_sub_C_splits_of_isPrimitiveRoot
      (((mem_primitiveRoots n.pos).1 hzeta).map_of_injective
        (algebraMap F E).injective) halpha
  · rw [eq_top_iff, ← IntermediateField.top_toSubalgebra, ← hgenerate,
      IntermediateField.adjoin_simple_toSubalgebra_of_isAlgebraic
        (IsAlgebraic.of_finite F alpha)]
    apply Algebra.adjoin_mono
    rw [Set.singleton_subset_iff,
      Polynomial.mem_rootSet_of_ne
        (Polynomial.X_pow_sub_C_ne_zero n.pos a),
      Polynomial.aeval_def, Polynomial.eval₂_sub, Polynomial.eval₂_X_pow,
      Polynomial.eval₂_C, halpha, sub_self]

theorem finitePlaceHilbert_natCast_ne_zero
    (n : ℕ+) (hnK : ((n : ℕ) : K) ≠ 0)
    (v : HeightOneSpectrum (𝓞 K)) :
    ((n : ℕ) :
        (NumberField.HeightOneSpectrum.adicAbv K v).Completion) ≠ 0 := by
  intro hn
  apply hnK
  apply
    (algebraMap K
      (NumberField.HeightOneSpectrum.adicAbv K v).Completion).injective
  simpa only [map_natCast, map_zero] using hn

theorem finitePlaceHilbert_primitiveRoots_nonempty
    (n : ℕ+) (hmu : (primitiveRoots (n : ℕ) K).Nonempty)
    (v : HeightOneSpectrum (𝓞 K)) :
    (primitiveRoots (n : ℕ)
      (NumberField.HeightOneSpectrum.adicAbv K v).Completion).Nonempty := by
  obtain ⟨zeta, hzeta⟩ := hmu
  refine ⟨algebraMap K
      (NumberField.HeightOneSpectrum.adicAbv K v).Completion zeta, ?_⟩
  apply (mem_primitiveRoots n.pos).2
  exact ((mem_primitiveRoots n.pos).1 hzeta).map_of_injective
    (algebraMap K
      (NumberField.HeightOneSpectrum.adicAbv K v).Completion).injective

/-- The image of a global unit in the canonical absolute-value completion
at a finite place. -/
noncomputable def finitePlaceHilbert_completionUnit
    (v : HeightOneSpectrum (𝓞 K)) (a : Kˣ) :
    (NumberField.HeightOneSpectrum.adicAbv K v).Completionˣ :=
  Units.map
    (algebraMap K
      (NumberField.HeightOneSpectrum.adicAbv K v).Completion).toMonoidHom a

/-- The local Hilbert-symbol value in the canonical absolute-value completion
at a finite place, before transport back to the number field. -/
noncomputable def finitePlaceLocalHilbertSymbol
    (n : ℕ+) (hnK : ((n : ℕ) : K) ≠ 0)
    (hmu : (primitiveRoots (n : ℕ) K).Nonempty)
    (v : HeightOneSpectrum (𝓞 K)) (a b : Kˣ) :
    nthRootsSubgroup
      (NumberField.HeightOneSpectrum.adicAbv K v).Completion (n : ℕ) := by
  let C := (NumberField.HeightOneSpectrum.adicAbv K v).Completion
  letI : ValuativeRel C :=
    finitePlaceLocalArtinCompletionValuativeRel v
  letI : IsNonarchimedeanLocalField C :=
    finitePlaceLocalArtinCompletionIsNonarchimedeanLocalField v
  exact
    LocalClassFieldTheory.Kummer.localHilbertSymbol C n
      (finitePlaceHilbert_natCast_ne_zero K n hnK v)
      (finitePlaceHilbert_primitiveRoots_nonempty K n hmu v)
      (finitePlaceHilbert_completionUnit K v a)
      (finitePlaceHilbert_completionUnit K v b)

/-- The Hilbert symbol of two global units at a finite place, evaluated in
the actual local completion and transported back to `μₙ(K)`. -/
noncomputable def finitePlaceHilbertSymbol
    (n : ℕ+) (hnK : ((n : ℕ) : K) ≠ 0)
    (hmu : (primitiveRoots (n : ℕ) K).Nonempty)
    (v : HeightOneSpectrum (𝓞 K)) (a b : Kˣ) :
    nthRootsSubgroup K (n : ℕ) :=
  (nthRootsSubgroupEquivOfPrimitiveRoots K
      (NumberField.HeightOneSpectrum.adicAbv K v).Completion n hmu).symm
    (finitePlaceLocalHilbertSymbol K n hnK hmu v a b)

/-- Extending the finite-place symbol to the completion recovers the
underlying local Hilbert symbol on the images of the two global units. -/
theorem finitePlaceHilbertSymbol_map_eq_localHilbertSymbol
    (n : ℕ+) (hnK : ((n : ℕ) : K) ≠ 0)
    (hmu : (primitiveRoots (n : ℕ) K).Nonempty)
    (v : HeightOneSpectrum (𝓞 K)) (a b : Kˣ) :
    nthRootsSubgroupMap K
        (NumberField.HeightOneSpectrum.adicAbv K v).Completion (n : ℕ)
        (finitePlaceHilbertSymbol K n hnK hmu v a b) =
      finitePlaceLocalHilbertSymbol K n hnK hmu v a b := by
  change
    (nthRootsSubgroupEquivOfPrimitiveRoots K
      (NumberField.HeightOneSpectrum.adicAbv K v).Completion n hmu)
        ((nthRootsSubgroupEquivOfPrimitiveRoots K
          (NumberField.HeightOneSpectrum.adicAbv K v).Completion n hmu).symm
            (finitePlaceLocalHilbertSymbol K n hnK hmu v a b)) =
      finitePlaceLocalHilbertSymbol K n hnK hmu v a b
  exact
    (nthRootsSubgroupEquivOfPrimitiveRoots K
      (NumberField.HeightOneSpectrum.adicAbv K v).Completion n hmu).apply_symm_apply _

/-- The global Kummer root character evaluated at the finite-place Artin
automorphism attached to a specified extension of the place.  Its value is
transported from the chosen global simple Kummer extension back to `μₙ(K)`.
-/
noncomputable def finitePlaceKummerRootCharacterOfExtension
    (n : ℕ+) (hnK : ((n : ℕ) : K) ≠ 0)
    (hmu : (primitiveRoots (n : ℕ) K).Nonempty)
    (v : HeightOneSpectrum (𝓞 K)) (a b : Kˣ)
    (w : AbsoluteValueExtension
      (NumberField.HeightOneSpectrum.adicAbv K v)
      (chosenSimpleKummerExtension K n hnK b)) :
    nthRootsSubgroup K (n : ℕ) := by
  let L := chosenSimpleKummerExtension K n hnK b
  letI : FiniteDimensional K L :=
    chosenSimpleKummerExtension_finiteDimensional K n hnK b
  letI : IsAbelianGalois K L :=
    chosenSimpleKummerExtension_isAbelianGalois K n hnK hmu b
  let a_v : (v.adicCompletion K)ˣ :=
    Units.map (algebraMap K (v.adicCompletion K)).toMonoidHom a
  exact
    (nthRootsSubgroupEquivOfPrimitiveRoots K L n hmu).symm
      (chosenSimpleKummerRootCharacter K n hnK hmu b
        (finitePlaceArtinMonoidHomOfExtension
          (K := K) (L := L) v w a_v))

/-- Changing the extension of the base absolute value does not change the
transported Kummer root-character value. -/
theorem finitePlaceKummerRootCharacterOfExtension_eq_of_extensions
    (n : ℕ+) (hnK : ((n : ℕ) : K) ≠ 0)
    (hmu : (primitiveRoots (n : ℕ) K).Nonempty)
    (v : HeightOneSpectrum (𝓞 K)) (a b : Kˣ)
    (w w' : AbsoluteValueExtension
      (NumberField.HeightOneSpectrum.adicAbv K v)
      (chosenSimpleKummerExtension K n hnK b)) :
    finitePlaceKummerRootCharacterOfExtension
        K n hnK hmu v a b w =
      finitePlaceKummerRootCharacterOfExtension
        K n hnK hmu v a b w' := by
  let L := chosenSimpleKummerExtension K n hnK b
  let : FiniteDimensional K L :=
    chosenSimpleKummerExtension_finiteDimensional K n hnK b
  let : IsAbelianGalois K L :=
    chosenSimpleKummerExtension_isAbelianGalois K n hnK hmu b
  let a_v : (v.adicCompletion K)ˣ :=
    Units.map (algebraMap K (v.adicCompletion K)).toMonoidHom a
  have hArtin := DFunLike.congr_fun
    (finitePlaceArtinMonoidHomOfExtension_eq
      (K := K) (L := L) v w w') a_v
  have hRoot := congrArg
    (chosenSimpleKummerRootCharacter K n hnK hmu b) hArtin
  unfold finitePlaceKummerRootCharacterOfExtension
  exact congrArg
    (nthRootsSubgroupEquivOfPrimitiveRoots K L n hmu).symm hRoot

/-- The finite-place Kummer root-character value obtained from the canonical
chosen extension of the base place. -/
noncomputable def finitePlaceKummerRootCharacter
    (n : ℕ+) (hnK : ((n : ℕ) : K) ≠ 0)
    (hmu : (primitiveRoots (n : ℕ) K).Nonempty)
    (v : HeightOneSpectrum (𝓞 K)) (a b : Kˣ) :
    nthRootsSubgroup K (n : ℕ) := by
  let L := chosenSimpleKummerExtension K n hnK b
  letI : FiniteDimensional K L :=
    chosenSimpleKummerExtension_finiteDimensional K n hnK b
  letI : IsAbelianGalois K L :=
    chosenSimpleKummerExtension_isAbelianGalois K n hnK hmu b
  exact
    finitePlaceKummerRootCharacterOfExtension K n hnK hmu v a b
      (chosenFinitePlaceExtension (L := L) v)

/-- The finite-place Kummer root-character value is independent of the
extension of the base absolute value used to construct the local Artin map.
-/
theorem finitePlaceKummerRootCharacterOfExtension_eq
    (n : ℕ+) (hnK : ((n : ℕ) : K) ≠ 0)
    (hmu : (primitiveRoots (n : ℕ) K).Nonempty)
    (v : HeightOneSpectrum (𝓞 K)) (a b : Kˣ)
    (w : AbsoluteValueExtension
      (NumberField.HeightOneSpectrum.adicAbv K v)
      (chosenSimpleKummerExtension K n hnK b)) :
    finitePlaceKummerRootCharacterOfExtension
        K n hnK hmu v a b w =
      finitePlaceKummerRootCharacter K n hnK hmu v a b := by
  let L := chosenSimpleKummerExtension K n hnK b
  let : FiniteDimensional K L :=
    chosenSimpleKummerExtension_finiteDimensional K n hnK b
  let : IsAbelianGalois K L :=
    chosenSimpleKummerExtension_isAbelianGalois K n hnK hmu b
  let w' := chosenFinitePlaceExtension (L := L) v
  unfold finitePlaceKummerRootCharacter
  exact finitePlaceKummerRootCharacterOfExtension_eq_of_extensions
    K n hnK hmu v a b w w'

end Reciprocity
end GlobalClassFieldTheory
