/-
Copyright (c) 2026 Naganori Yamaguchi (https://github.com/n-yamaguchi-0729). All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Naganori Yamaguchi (assisted by OpenAI Codex)
-/

import ClassFieldTheory.Theorems.HilbertSymbols.PowerClassEqOneIff
import ClassFieldTheory.Theorems.HilbertSymbols.PowerClassMul
import ClassFieldTheory.Theorems.HilbertSymbols.PowerClassInv
import ClassFieldTheory.Theorems.HilbertSymbols.PowerClassPow
import ClassFieldTheory.Theorems.HilbertSymbols.PowerClassEqIff
import ClassFieldTheory.Theorems.HilbertSymbols.HilbertPairingSymbolMul
import ClassFieldTheory.Theorems.HilbertSymbols.HilbertPairingSymbolMulRight
import ClassFieldTheory.Theorems.HilbertSymbols.HilbertPairingPerfect
import ClassFieldTheory.Theorems.HilbertSymbols.LocalHilbertPairingExists
import ClassFieldTheory.Theorems.HilbertSymbols.LocalHilbertPairingArtinNormalization
import ClassFieldTheory.Theorems.HilbertSymbols.LocalHilbertPairingExponentCompatibility
import ClassFieldTheory.Theorems.HilbertSymbols.RootQuotientChoiceIndependence
import ClassFieldTheory.Theorems.HilbertSymbols.LocalHilbertPairingInverse
import ClassFieldTheory.Theorems.HilbertSymbols.LocalHilbertPairingNormCriterion
import ClassFieldTheory.Theorems.HilbertSymbols.LocalHilbertPairingPerfectExists
import ClassFieldTheory.Theorems.HilbertSymbols.HilbertProductFormula
import ClassFieldTheory.Theorems.HilbertSymbols.GlobalHilbertPairingFiniteSupport
import ClassFieldTheory.Theorems.HilbertSymbols.FinitePlaceHilbertBadSetFinite
import ClassFieldTheory.Theorems.HilbertSymbols.GlobalHilbertPairingSupportBound
import ClassFieldTheory.Theorems.HilbertSymbols.KummerAlgebraFiniteFree
import ClassFieldTheory.Theorems.HilbertSymbols.KummerAlgebraFiniteEtale
import ClassFieldTheory.Theorems.HilbertSymbols.KummerAlgebraProductDecomposition
import ClassFieldTheory.Theorems.HilbertSymbols.KummerAlgebraUniformFieldFactors
import ClassFieldTheory.Theorems.HilbertSymbols.KummerAlgebraUniformFactorDegree
import ClassFieldTheory.Theorems.HilbertSymbols.KummerAlgebraCopiesOfSimpleFactor
import ClassFieldTheory.Theorems.HilbertSymbols.KummerAlgebraNormProduct
import ClassFieldTheory.Theorems.HilbertSymbols.KummerAlgebraFinrank
import ClassFieldTheory.Theorems.HilbertSymbols.KummerAlgebraNormIffSimpleRadicalNorm
import ClassFieldTheory.Theorems.HilbertSymbols.KummerAlgebraNormIndex
import ClassFieldTheory.Theorems.HilbertSymbols.KummerRadicalDegreeEqPowerClassOrder
import ClassFieldTheory.Theorems.HilbertSymbols.KummerAlgebraOneNormSurjective
import ClassFieldTheory.Theorems.HilbertSymbols.PowerClassGroupFinite

set_option autoImplicit false

/-!
# Hilbert symbols

This `All` module collects the power-class quotient theorem, existence and
the norm-residue criterion for local Hilbert pairings, and existence of a
coherent family satisfying the global product formula.
-/
