/-
Copyright (c) 2026 Naganori Yamaguchi (https://github.com/n-yamaguchi-0729). All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Naganori Yamaguchi (assisted by OpenAI Codex)
-/

import ClassFieldTheory.Definitions.HilbertSymbols.KummerAlgebraNormSubgroup
import ClassFieldTheory.LocalClassFieldTheory.Kummer.SmallHilbertPairingTransport
import ClassFieldTheory.Theorems.HilbertSymbols.HilbertPairingPerfect
import ClassFieldTheory.Theorems.HilbertSymbols.PowerClassGroupFinite
import Mathlib.GroupTheory.SpecificGroups.Cyclic.Basic
import Mathlib.NumberTheory.LocalField.Basic

set_option autoImplicit false

/-!
# Degree of a Kummer radical and order of its power class

The order of the class of `a` is the degree of the field generated by an
`n`-th root of `a`.  The associated Kummer algebra need not be a field: in
particular, the class of `a = 1` has order one even when the algebra has
rank `n`.
-/

noncomputable section

namespace ClassFieldTheory

universe u

/-- Over a nonarchimedean local field containing `μₙ`, the norm index of
`K[X]/(Xⁿ-a)` is the order of the class of `a` modulo `n`-th powers. -/
theorem kummerAlgebraNormSubgroup_index_eq_powerClassOrder
    (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K]
    (n : ℕ+) (hnK : ((n : ℕ) : K) ≠ 0)
    (hmu : (primitiveRoots (n : ℕ) K).Nonempty) (a : Kˣ) :
    (kummerAlgebraNormSubgroup K n a).index =
      orderOf (powerClass K n a) := by
  let : Small.{0} K := LocalFieldTheory.nonarchimedeanLocalField_small K
  let S := Shrink.{0} K
  let : ValuativeRel S := LocalFieldTheory.shrinkLocalFieldValuativeRel K
  let : IsNonarchimedeanLocalField S :=
    LocalFieldTheory.shrinkLocalField_isNonarchimedeanLocalField K
  let e : S ≃+* K := Shrink.ringEquiv K
  have hnS : ((n : ℕ) : S) ≠ 0 := by
    intro hz
    apply hnK
    have hzK := congrArg e hz
    simpa [e] using hzK
  have hmuS : (primitiveRoots (n : ℕ) S).Nonempty := by
    obtain ⟨ζ, hζ⟩ := hmu
    refine ⟨e.symm ζ, ?_⟩
    exact (mem_primitiveRoots n.pos).2
      (((mem_primitiveRoots n.pos).1 hζ).map_of_injective e.symm.injective)
  let B₀ : HilbertPairing S n := localHilbertPairing S n hnS hmuS
  let B : HilbertPairing K n := hilbertPairingOfRingEquiv e n hmuS B₀
  have hB : HilbertPairing.IsLocalHilbertPairing B :=
    hilbertPairingOfRingEquiv_isLocalHilbertPairing e n hmuS B₀
      (localHilbertPairing_isLocalHilbertPairing S n hnS hmuS)
  let : Finite (PowerClassGroup K n) := powerClassGroup_finite K n hnK
  have hBbij : Function.Bijective B := hB.2.2.1.bijective hmu
  let x : PowerClassGroup K n := powerClass K n a
  let ψ : PowerClassGroup K n →* rootsOfUnity (n : ℕ) K := B x
  have hnorm :
      kummerAlgebraNormSubgroup K n a =
        ψ.ker.comap (powerClass K n) := by
    ext b
    change
      (∃ y : (KummerAlgebra K n a)ˣ,
        Units.map (Algebra.norm K) y = b) ↔ B.symbol a b = 1
    constructor
    · rintro ⟨y, hy⟩
      apply (hB.2.2.2 a b).2
      exact ⟨y, congrArg Units.val hy⟩
    · intro hb
      obtain ⟨y, hy⟩ := (hB.2.2.2 a b).1 hb
      refine ⟨y, ?_⟩
      apply Units.ext
      exact hy
  have hpowerClass : Function.Surjective (powerClass K n) := by
    change Function.Surjective
      (QuotientGroup.mk'
        (powMonoidHom (n : ℕ) : Kˣ →* Kˣ).range)
    exact QuotientGroup.mk'_surjective _
  have hψOrder : orderOf ψ = orderOf x := by
    simpa [ψ] using orderOf_injective B hBbij.1 x
  have hcardRange : Nat.card ψ.range = orderOf ψ := by
    apply Nat.dvd_antisymm
    · obtain ⟨g, hg⟩ := IsCyclic.exists_generator (α := ψ.range)
      rw [← orderOf_eq_card_of_forall_mem_zpowers hg]
      obtain ⟨y, hy⟩ := g.property
      calc
        orderOf g = orderOf (g : rootsOfUnity (n : ℕ) K) :=
          (Subgroup.orderOf_coe g).symm
        _ = orderOf (ψ y) := by rw [hy]
        _ ∣ orderOf ψ := by
          apply orderOf_dvd_of_pow_eq_one
          have hp := congrArg
            (fun f : PowerClassGroup K n →* rootsOfUnity (n : ℕ) K => f y)
            (pow_orderOf_eq_one ψ)
          simpa only [MonoidHom.pow_apply, MonoidHom.one_apply] using hp
    · apply orderOf_dvd_of_pow_eq_one
      apply MonoidHom.ext
      intro y
      change ψ y ^ Nat.card ψ.range = 1
      let z : ψ.range := ⟨ψ y, ⟨y, rfl⟩⟩
      have hz : z ^ Nat.card ψ.range = 1 := pow_card_eq_one'
      simpa [z] using congrArg Subtype.val hz
  calc
    (kummerAlgebraNormSubgroup K n a).index =
        (ψ.ker.comap (powerClass K n)).index :=
      congrArg (fun H : Subgroup Kˣ ↦ H.index) hnorm
    _ = ψ.ker.index := ψ.ker.index_comap_of_surjective hpowerClass
    _ = Nat.card ψ.range := Subgroup.index_ker ψ
    _ = orderOf ψ := hcardRange
    _ = orderOf (powerClass K n a) := by simpa [x] using hψOrder

end ClassFieldTheory
