/-
Copyright (c) 2026 Naganori Yamaguchi (https://github.com/n-yamaguchi-0729). All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Naganori Yamaguchi (assisted by OpenAI Codex)
-/

import ClassFieldTheory.Definitions.HilbertSymbols.KummerAlgebra
import ClassFieldTheory.LocalClassFieldTheory.Kummer.CanonicalKummerNorm

set_option autoImplicit false

/-!
# Norms from a Kummer algebra and a simple radical field

The canonical algebra `K[X] / (X^n - a)` need not be a field.  When `K`
contains the `n`-th roots of unity and `n` is nonzero in `K`, its norm image
on units nevertheless agrees with the norm image of a field generated by an
`n`-th root of `a`.  One root works simultaneously for every target value.
-/

namespace ClassFieldTheory

/-- There is an `n`-th root of `a` whose simple radical extension has exactly
the same norm values on units as the possibly reducible Kummer algebra. -/
theorem kummerAlgebra_norm_iff_simpleRadicalNorm
    (K : Type) [Field K] (n : ℕ+)
    (hnK : ((n : ℕ) : K) ≠ 0)
    (hmu : (primitiveRoots (n : ℕ) K).Nonempty) (a : Kˣ) :
    ∃ β : SeparableClosure K,
      β ^ (n : ℕ) = algebraMap K (SeparableClosure K) (a : K) ∧
      ∀ b : Kˣ,
        (∃ y : (KummerAlgebra K n a)ˣ,
          Algebra.norm K (y : KummerAlgebra K n a) = (b : K)) ↔
        ∃ z : (IntermediateField.adjoin K {β})ˣ,
          Algebra.norm K (z.val : IntermediateField.adjoin K {β}) = (b : K) := by
  refine ⟨KummerTheory.chosenSimpleKummerRoot K n hnK a,
    KummerTheory.chosenSimpleKummerRoot_pow K n hnK a, ?_⟩
  intro b
  exact LocalClassFieldTheory.Kummer.adjoinRoot_norm_iff_chosenSimpleKummerNorm
    K n hnK hmu a b

end ClassFieldTheory
