/-
Copyright (c) 2026 Naganori Yamaguchi (https://github.com/n-yamaguchi-0729). All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Naganori Yamaguchi (assisted by OpenAI Codex)
-/

import ClassFieldTheory.Definitions.HilbertSymbols.KummerAlgebraNormSubgroup
import ClassFieldTheory.LocalClassFieldTheory.Kummer.KummerNormPowerClassDegree
import Mathlib.NumberTheory.LocalField.Basic

set_option autoImplicit false

/-!
# Norm index of a Kummer algebra

The degree of `K[X] / (X^n - a)` is always `n`, but its norm image can
have smaller index.  Over a nonarchimedean local field containing the
`n`-th roots of unity, the index is instead the degree of the simple
field generated by an `n`-th root of `a`.
-/

noncomputable section

namespace ClassFieldTheory

/-- The unit-norm image of a possibly reducible Kummer algebra has index
equal to the degree of a simple radical field, not necessarily `n`. -/
theorem kummerAlgebraNormSubgroup_index_eq_radicalDegree
    (K : Type) [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K]
    (n : ℕ+) (hnK : ((n : ℕ) : K) ≠ 0)
    (hmu : (primitiveRoots (n : ℕ) K).Nonempty) (a : Kˣ) :
    ∃ β : SeparableClosure K,
      β ^ (n : ℕ) = algebraMap K (SeparableClosure K) (a : K) ∧
      (kummerAlgebraNormSubgroup K n a).index =
        Module.finrank K (IntermediateField.adjoin K {β}) := by
  exact ⟨KummerTheory.chosenSimpleKummerRoot K n hnK a,
    KummerTheory.chosenSimpleKummerRoot_pow K n hnK a,
    LocalClassFieldTheory.Kummer.kummerAlgebraNormSubgroup_index_eq_chosenRadicalDegree
      K n hnK hmu a⟩

end ClassFieldTheory
