/-
Copyright (c) 2026 Naganori Yamaguchi (https://github.com/n-yamaguchi-0729). All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Naganori Yamaguchi (assisted by OpenAI Codex)
-/

import ClassFieldTheory.LocalClassFieldTheory.Finite.Existence.CharacteristicZero
import ClassFieldTheory.LocalClassFieldTheory.Finite.Existence.Classification
import ClassFieldTheory.LocalClassFieldTheory.Finite.Existence.CyclotomicKummerDescent
import ClassFieldTheory.LocalClassFieldTheory.Finite.Existence.EqualCharacteristic
import ClassFieldTheory.LocalClassFieldTheory.Finite.Existence.EqualCharacteristicDominatingExtension
import ClassFieldTheory.LocalClassFieldTheory.Finite.Existence.FiniteUnramifiedField
import ClassFieldTheory.LocalClassFieldTheory.Finite.Existence.KummerNormOpen
import ClassFieldTheory.LocalClassFieldTheory.Finite.Existence.LocalAbsoluteData
import ClassFieldTheory.LocalClassFieldTheory.Finite.Existence.LubinTateUniformizerDiagonal
import ClassFieldTheory.LocalClassFieldTheory.Finite.Existence.MathlibFieldClassification
import ClassFieldTheory.LocalClassFieldTheory.Finite.Existence.MaximalKummerNorm
import ClassFieldTheory.LocalClassFieldTheory.Finite.Existence.NormSubgroupOrderEmbedding
import ClassFieldTheory.LocalClassFieldTheory.Finite.Existence.NormSubgroupRingEquiv
import ClassFieldTheory.LocalClassFieldTheory.Finite.Existence.NormSubgroupSurjectivity
import ClassFieldTheory.LocalClassFieldTheory.Finite.Existence.OrderReversal
import ClassFieldTheory.LocalClassFieldTheory.Finite.Existence.ShrinkChosenFiniteAbelianFields
import ClassFieldTheory.LocalClassFieldTheory.Finite.Existence.ShrinkChosenFiniteAbelianNorms
import ClassFieldTheory.LocalClassFieldTheory.Finite.Existence.ShrinkFiniteAbelianFields
import ClassFieldTheory.LocalClassFieldTheory.Finite.Existence.ShrinkFiniteAbelianNorms
import ClassFieldTheory.LocalClassFieldTheory.Finite.Existence.ShrinkIntermediateFields
import ClassFieldTheory.LocalClassFieldTheory.Finite.Existence.ShrinkLocalClassification
import ClassFieldTheory.LocalClassFieldTheory.Finite.Existence.ShrinkOpenSubgroups
import ClassFieldTheory.LocalClassFieldTheory.Finite.Existence.ShrinkSeparableClosure
import ClassFieldTheory.LocalClassFieldTheory.Finite.Existence.StandardDominatingExtension
import ClassFieldTheory.LocalClassFieldTheory.Finite.Existence.StandardLubinTate
import ClassFieldTheory.LocalClassFieldTheory.Finite.Existence.StandardSubgroupIntersection
import ClassFieldTheory.LocalClassFieldTheory.Finite.Existence.UnramifiedLubinTateDiagonal
import ClassFieldTheory.LocalClassFieldTheory.Finite.Existence.UnramifiedNormContainment
import ClassFieldTheory.LocalClassFieldTheory.Finite.Existence.UnramifiedNormSubgroup
import ClassFieldTheory.LocalClassFieldTheory.Finite.Existence.UnshrinkFiniteAbelianFields

set_option autoImplicit false

/-!
# Finite local existence theorem

The ordinary norm-subgroup assignment is an order embedding into the
opposite poset of native open finite-index subgroups.  Kummer theory in
characteristic zero and transported Lubin--Tate levels in positive
characteristic prove the existing characteristic-specific order
isomorphisms.  The canonical standard Lubin--Tate construction now also
provides a characteristic-independent finite abelian factor with its exact
norm subgroup.
-/
