/-
Copyright (c) 2026 Naganori Yamaguchi (https://github.com/n-yamaguchi-0729). All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Naganori Yamaguchi (assisted by OpenAI Codex)
-/

import ClassFieldTheory.Definitions.HilbertSymbols.GlobalHilbertPairingFamily
import ClassFieldTheory.Definitions.HilbertSymbols.GlobalHilbertPairingFiniteFactor
import ClassFieldTheory.Definitions.HilbertSymbols.GlobalHilbertPairingProperties
import ClassFieldTheory.Definitions.HilbertSymbols.GlobalInfinitePlaceHilbertSymbol
import ClassFieldTheory.Definitions.HilbertSymbols.FinitePlaceHilbertBadSet
import ClassFieldTheory.Definitions.HilbertSymbols.HilbertPairing
import ClassFieldTheory.Definitions.HilbertSymbols.HilbertPairingLaws
import ClassFieldTheory.Definitions.HilbertSymbols.HilbertPairingNormResidueCriterion
import ClassFieldTheory.Definitions.HilbertSymbols.HilbertPairingSymbol
import ClassFieldTheory.Definitions.HilbertSymbols.IsKummerNorm
import ClassFieldTheory.Definitions.HilbertSymbols.IsLocalHilbertPairing
import ClassFieldTheory.Definitions.HilbertSymbols.KummerAlgebra
import ClassFieldTheory.Definitions.HilbertSymbols.KummerAlgebraNormSubgroup
import ClassFieldTheory.Definitions.HilbertSymbols.PowerClass
import ClassFieldTheory.Definitions.HilbertSymbols.PowerClassGroup

set_option autoImplicit false
