/-
Copyright (c) 2026 Naganori Yamaguchi (https://github.com/n-yamaguchi-0729). All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Naganori Yamaguchi (assisted by OpenAI Codex)
-/

import ClassFieldTheory.Definitions.ConductorsAndRayClassFields.IsRayCongruent
import ClassFieldTheory.Definitions.ConductorsAndRayClassFields.RayClassPrimeToIdeals
import Mathlib.RingTheory.ClassGroup.Basic

set_option autoImplicit false

/-!
# Ray-principal ideals
-/

open scoped NumberField
open NumberField

namespace ClassFieldTheory

universe u

/-- The subgroup generated by principal fractional ideals whose generators
satisfy the ray congruence. -/
def rayPrincipalIdealSubgroup
    {K : Type u} [Field K] [NumberField K]
    (m : RayClassModulus K) :
    Subgroup (NumberFieldFractionalIdealGroup K) :=
  Subgroup.closure
    {I | ∃ x : Kˣ,
      IsRayCongruent m x ∧ toPrincipalIdeal (𝓞 K) K x = I}

/-- Ray-principal ideals, restricted to the group of ideals prime to the
modulus. -/
def rayPrincipalIdealSubgroupInPrimeTo
    {K : Type u} [Field K] [NumberField K]
    (m : RayClassModulus K) :
    Subgroup (rayClassPrimeToIdeals m) :=
  Subgroup.comap (rayClassPrimeToIdeals m).subtype
    (rayPrincipalIdealSubgroup m)

end ClassFieldTheory
