/-
Copyright (c) 2026 Naganori Yamaguchi (https://github.com/n-yamaguchi-0729). All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Naganori Yamaguchi (assisted by OpenAI Codex)
-/

import ClassFieldTheory.KroneckerWeber.Core
import ClassFieldTheory.KroneckerWeber.Final
import ClassFieldTheory.KroneckerWeber.GlobalCompositumCyclotomicTarget
import ClassFieldTheory.KroneckerWeber.GlobalCompositumGlobalEmbedding
import ClassFieldTheory.KroneckerWeber.GlobalCompositumLeftFactors
import ClassFieldTheory.KroneckerWeber.GlobalCompositumLocalizationEmbedding
import ClassFieldTheory.KroneckerWeber.GlobalCompositumValuationInertiaBound
import ClassFieldTheory.KroneckerWeber.GlobalCompositumValuedEmbedding
import ClassFieldTheory.KroneckerWeber.GlobalPadicPrimePowInertiaBound
import ClassFieldTheory.KroneckerWeber.LocalCyclotomicEmbedding
import ClassFieldTheory.KroneckerWeber.RationalCyclotomicArithmeticReciprocity
import ClassFieldTheory.KroneckerWeber.RationalRayClassFieldCyclotomic
import ClassFieldTheory.KroneckerWeber.RayClassComparison
import ClassFieldTheory.KroneckerWeber.Setup
import ClassFieldTheory.KroneckerWeber.UnramifiedCompositumSupport

set_option autoImplicit false
