/-
Copyright (c) 2026 Naganori Yamaguchi (https://github.com/n-yamaguchi-0729). All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Naganori Yamaguchi (assisted by OpenAI Codex)
-/

import ClassFieldTheory.LocalClassFieldTheory.ClassFormation.ArchimedeanHilbert90
import ClassFieldTheory.LocalClassFieldTheory.ClassFormation.ArchimedeanNormQuotient
import ClassFieldTheory.LocalClassFieldTheory.ClassFormation.CohomologyBridge
import ClassFieldTheory.LocalClassFieldTheory.ClassFormation.FieldUnitsHerbrand
import ClassFieldTheory.LocalClassFieldTheory.ClassFormation.FilteredLiftingSequence
import ClassFieldTheory.LocalClassFieldTheory.ClassFormation.Hilbert90
import ClassFieldTheory.LocalClassFieldTheory.ClassFormation.IntegerUnitsHerbrand
import ClassFieldTheory.LocalClassFieldTheory.ClassFormation.LocalBlocks.All
import ClassFieldTheory.LocalClassFieldTheory.ClassFormation.LocalizedCompletionCohomology.All
import ClassFieldTheory.LocalClassFieldTheory.ClassFormation.Main
import ClassFieldTheory.LocalClassFieldTheory.ClassFormation.NormalBasis
import ClassFieldTheory.LocalClassFieldTheory.ClassFormation.NormalBasisCohomology
import ClassFieldTheory.LocalClassFieldTheory.ClassFormation.NormalBasisFiniteQuotient
import ClassFieldTheory.LocalClassFieldTheory.ClassFormation.NormalBasisGaloisAction
import ClassFieldTheory.LocalClassFieldTheory.ClassFormation.NormalBasisGradedLifting
import ClassFieldTheory.LocalClassFieldTheory.ClassFormation.NormalBasisInfiniteProduct
import ClassFieldTheory.LocalClassFieldTheory.ClassFormation.NormalBasisRecursiveLifting
import ClassFieldTheory.LocalClassFieldTheory.ClassFormation.PrincipalUnitGraded
import ClassFieldTheory.LocalClassFieldTheory.ClassFormation.Valuation
import ClassFieldTheory.LocalClassFieldTheory.ClassFormation.ValuationHerbrand
import ClassFieldTheory.LocalClassFieldTheory.ClassFormation.ValueGroupCohomology

set_option autoImplicit false

/-!
# The local class formation

Public aggregate for the normal-basis, unit-filtration, valuation, and
cohomology calculations establishing the local class-field axiom.
-/
