/-
Copyright (c) 2026 Naganori Yamaguchi (https://github.com/n-yamaguchi-0729). All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Naganori Yamaguchi (assisted by OpenAI Codex)
-/

import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.AbelianConductorExactness
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.AbelianConductorRamification
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.AbelianLocalConductorComparison
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.AbelianNormConductor
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.ArithmeticClassFieldCorrespondence
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.ArithmeticHilbertClassFieldReciprocity
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.ArithmeticRayClassFieldReciprocity
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.ArithmeticUnramifiedPrimeArtin
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.BigHilbertClassField
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.BigHilbertClassFieldMathlibArtin
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.BigHilbertClassFieldNaturality
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.BigHilbertClassFieldOverOriginalBase
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.ClassFieldRealization
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.ClosedFiniteIndexClassFieldConstruction
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.ClosedFiniteIndexClassFieldNormRange
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.ClosedFiniteIndexClassFieldOriginalField
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.ClosedFiniteIndexClassFieldReciprocity.All
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.Conductor
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.ConductorFrobenius
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.ConductorInfinitePart
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.ConductorLattice
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.ConductorLocalComparison
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.ConductorPrimeArtin
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.ConductorRayClassMaximality
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.ConductorSupport
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.CyclicConductorUniqueness
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.CyclicNormConductor
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.CyclicNormTower
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.CyclicRayClassMaximality
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.CyclotomicKummerNormDescent
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.EmbeddedAbelianSubextension
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.FiniteAbelianClassFieldContainment
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.FiniteAbelianClassFieldCorrespondence
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.FiniteAbelianClassFieldCorrespondenceTopology
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.FiniteIndexNormClassField
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.FinitePlaceArtinQuotient
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.FullConductorRayClassField
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.HilbertClassFieldComparison
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.HilbertClassFieldMaximalSubextension
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.HilbertClassFieldMaximality
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.HilbertClassFieldPrimeSplitting
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.HilbertClassFieldRealization
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.HilbertClassFieldReciprocity.All
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.HilbertClassFieldUnramifiedMaximality
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.HilbertNormCharacterization
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.InfiniteAbelianClassFieldCorrespondence
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.KummerNormDescent
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.MathlibFrobeniusHilbertComparison
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.MathlibGlobalReciprocity
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.NormConductor
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.NormLimitation
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.NormRayClassMaximality
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.NormTowerConductor
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.OrdinaryNormClassField
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.PowerCongruenceCore
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.PublicIdealArtinKernelComparison
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.PublicIdealNormArtinKernel
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.PublicIdealNormQuotientComparison
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.PublicRayClassComparison
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.RationalRayPrimeClass
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.RayClassFieldRealization
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.RayClassModulusProjection
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.RayClassPrimeIdele
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.RayClassSubgroupFieldAntitone
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.RayClassSubgroupPrimeArtin
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.RayFrobeniusRigidity
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.RayPrimeGeneration
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.SUnitKummerNormCore
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.SUnitKummerNormRealization
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.SmallHilbertClassField
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.SmallHilbertClassFieldMaximalSubextension
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.SmallHilbertClassFieldNaturality
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.SmallHilbertClassFieldOverOriginalBase
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.SmallHilbertClassFieldMathlibArtin
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.SmallHilbertNormCharacterization
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.UnramifiedPrimeArtin
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.UnramifiedPrimeNormClass

set_option autoImplicit false

/-!
# Global class fields

This public root exports the finite abelian class-field correspondence for
closed finite-index idèle-class subgroups, exact conductor and ramification
theory, and the actual big and small Hilbert class fields with their maximality
and reciprocity characterizations.
-/
