/-
Copyright (c) 2026 Naganori Yamaguchi (https://github.com/n-yamaguchi-0729). All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Naganori Yamaguchi (assisted by OpenAI Codex)
-/

import ClassFieldTheory.AlgebraicNumberTheory.Idele.FinitePrime
import ClassFieldTheory.AlgebraicNumberTheory.Ramification.RationalPrime
import ClassFieldTheory.AlgebraicNumberTheory.RayClass.Rational
import ClassFieldTheory.AlgebraicNumberTheory.RayClass.Topology
import ClassFieldTheory.GlobalClassFieldTheory.GlobalClassFields.RayClassPrimeIdele

set_option autoImplicit false

/-!
# Rational prime classes in rational ray class groups

For a prime `q` away from a rational modulus `(m)`, the normalized
one-place prime idèle represents the direct residue unit `q` in
`(ZMod m)ˣ`.  This is the ideal-theoretic arithmetic input needed to
compare rational ray reciprocity with the cyclotomic character.
-/

open scoped Classical NumberField

noncomputable section

namespace GlobalClassFieldTheory
namespace GlobalClassFields

open NumberField IsDedekindDomain IdeleGroup

/-- The canonical rational ray-class identification, with the native
quotient topology on the idèle-class quotient and the finite discrete
topology on `(ZMod m)ˣ`.  Thus this is the topological form of the
rational ray-class computation, not only an abstract finite-group
isomorphism. -/
noncomputable def rationalRayClassGroupContinuousMulEquivZModUnits
    (m : ℕ) (hm : m ≠ 0) :
    RayClass.RayClassGroup (RayClass.rationalModulus m) ≃ₜ*
      (ZMod m)ˣ := by
  letI : DiscreteTopology
      (RayClass.RayClassGroup
        (RayClass.rationalModulus m)) :=
    QuotientGroup.discreteTopology
      (RayClass.isOpen_congruenceSubgroup
        (RayClass.rationalModulus m))
  exact
    { RayClass.rationalRayClassGroupEquivZModUnits m hm with
      continuous_toFun := continuous_of_discreteTopology
      continuous_invFun := continuous_of_discreteTopology }

/-- Forgetting topology from the canonical rational ray-class
identification recovers the standard residue-class equivalence
literally. -/
@[simp]
theorem rationalRayClassGroupContinuousMulEquivZModUnits_apply
    (m : ℕ) (hm : m ≠ 0)
    (c : RayClass.RayClassGroup
      (RayClass.rationalModulus m)) :
    rationalRayClassGroupContinuousMulEquivZModUnits m hm c =
      RayClass.rationalRayClassGroupEquivZModUnits m hm c := by
  rfl

/-- A rational prime not dividing `m` is outside the finite support of
the rational modulus `(m)`. -/
theorem rationalPrime_not_mem_rationalModulus_support
    (m : ℕ) (hm : m ≠ 0)
    (q : Nat.Primes) (hq : ¬ q.1 ∣ m) :
    RayClass.rationalPrime q ∉
      (RayClass.rationalModulus m).finitePart.support := by
  intro hmem
  apply hq
  have hdiv :=
    (RayClass.mem_rationalFiniteModulus_support_iff
      hm (RayClass.rationalPrime q)).mp (by
        simpa only [RayClass.rationalModulus,
          RayClass.Modulus.finitePart_narrowOfFinite] using hmem)
  simpa only [RayClass.natGenerator_rationalPrime] using hdiv

/-- The height-one prime of `𝓞 ℚ` indexed by `q` is generated by the
integer `q`, transported through the canonical equivalence
`𝓞 ℚ ≃+* ℤ`. -/
theorem rationalPrime_asIdeal_eq_span_integerGenerator
    (q : Nat.Primes) :
    (RayClass.rationalPrime q).asIdeal =
      Ideal.span
        {Rat.ringOfIntegersEquiv.symm (q.1 : ℤ)} := by
  let v : HeightOneSpectrum (𝓞 ℚ) :=
    RayClass.rationalPrime q
  have hIntEquiv :
      Rat.IsIntegralClosure.intEquiv (𝓞 ℚ) =
        Rat.ringOfIntegersEquiv := by
    ext x
    exact
      Rat.IsIntegralClosure.intEquiv_apply_eq_ringOfIntegersEquiv x
  have hspan :
      Ideal.span {(q.1 : ℤ)} =
        v.asIdeal.map Rat.ringOfIntegersEquiv := by
    simpa only [v, RayClass.natGenerator_rationalPrime,
      hIntEquiv] using
      Rat.HeightOneSpectrum.span_natGenerator v
  apply
    ((RingEquiv.idealComapOrderIso
      Rat.ringOfIntegersEquiv).symm).injective
  simp only [RingEquiv.idealComapOrderIso_symm_apply]
  calc
    (RayClass.rationalPrime q).asIdeal.map
          Rat.ringOfIntegersEquiv =
        Ideal.span {(q.1 : ℤ)} := by
      simpa only [v] using hspan.symm
    _ =
      (Ideal.span
          {Rat.ringOfIntegersEquiv.symm (q.1 : ℤ)}).map
            Rat.ringOfIntegersEquiv := by
      rw [Ideal.map_span, Set.image_singleton,
        Rat.ringOfIntegersEquiv.apply_symm_apply]

/-- The fractional prime ideal indexed by `q` is literally the
principal fractional ideal generated by the positive rational integer
`q`. -/
theorem rationalPrime_fractionalIdeal_eq_toPrincipalIdeal
    (q : Nat.Primes) :
    FractionalIdealGroup.prime (RayClass.rationalPrime q) =
      toPrincipalIdeal (𝓞 ℚ) ℚ
        (Units.mk0 (q.1 : ℚ)
          (by exact_mod_cast q.2.ne_zero)) := by
  apply Units.ext
  rw [coe_toPrincipalIdeal]
  change
    ((RayClass.rationalPrime q).asIdeal :
        FractionalIdeal
          (nonZeroDivisors (𝓞 ℚ)) ℚ) =
      FractionalIdeal.spanSingleton
        (nonZeroDivisors (𝓞 ℚ)) (q.1 : ℚ)
  rw [rationalPrime_asIdeal_eq_span_integerGenerator,
    FractionalIdeal.coeIdeal_span_singleton]
  congr 1
  exact Rat.ringOfIntegersEquiv_symm_apply_coe (q.1 : ℤ)

/-- The rational prime ideal, regarded as prime to `(m)`, written using
its positive principal generator `q`. -/
noncomputable def rationalPrimePrincipalPrimeToModulusIdeal
    (m : ℕ) (hm : m ≠ 0)
    (q : Nat.Primes) (hq : ¬ q.1 ∣ m) :
    RayClass.primeToModulusIdeals
      (RayClass.rationalModulus m) :=
  ⟨toPrincipalIdeal (𝓞 ℚ) ℚ
      (Units.mk0 (q.1 : ℚ)
        (by exact_mod_cast q.2.ne_zero)),
    RayClass.principalNat_mem_primeToModulusIdeals
      hm q.2.ne_zero
        (q.2.coprime_iff_not_dvd.mpr hq)⟩

/-- The canonical prime-to-modulus ideal at `q` agrees with the
principal ideal represented by the positive integer `q`. -/
theorem primeToModulusIdeal_rationalPrime_eq_principal
    (m : ℕ) (hm : m ≠ 0)
    (q : Nat.Primes) (hq : ¬ q.1 ∣ m) :
    RayClass.primeToModulusIdeal
        (RayClass.rationalModulus m)
        (RayClass.rationalPrime q)
        (rationalPrime_not_mem_rationalModulus_support
          m hm q hq) =
      rationalPrimePrincipalPrimeToModulusIdeal
        m hm q hq := by
  apply Subtype.ext
  exact rationalPrime_fractionalIdeal_eq_toPrincipalIdeal q

/-- The ideal residue homomorphism sends the rational prime ideal at
`q ∤ m` to the direct residue unit `q`. -/
@[simp]
theorem primeToIdealResidueHom_rationalPrime
    (m : ℕ) (hm : m ≠ 0)
    (q : Nat.Primes) (hq : ¬ q.1 ∣ m) :
    RayClass.primeToIdealResidueHom m hm
        (RayClass.primeToModulusIdeal
          (RayClass.rationalModulus m)
          (RayClass.rationalPrime q)
          (rationalPrime_not_mem_rationalModulus_support
            m hm q hq)) =
      ZMod.unitOfCoprime q.1
        (q.2.coprime_iff_not_dvd.mpr hq) := by
  rw [primeToModulusIdeal_rationalPrime_eq_principal m hm q hq]
  rw [RayClass.primeToIdealResidueHom_apply]
  apply Units.ext
  change
    (RayClass.rationalResidueUnit m
        (RayClass.positiveRationalIdealGenerator
          (toPrincipalIdeal (𝓞 ℚ) ℚ
            (Units.mk0 (q.1 : ℚ)
              (by exact_mod_cast q.2.ne_zero)))) _ _ :
      ZMod m) =
        (ZMod.unitOfCoprime q.1
          (q.2.coprime_iff_not_dvd.mpr hq) : ZMod m)
  have hgen :
      RayClass.positiveRationalIdealGenerator
          (toPrincipalIdeal (𝓞 ℚ) ℚ
            (Units.mk0 (q.1 : ℚ)
              (by exact_mod_cast q.2.ne_zero))) =
        (q.1 : ℚ) :=
    RayClass.positiveGenerator_toPrincipalIdeal_nat q.2.pos
  have hcop : Nat.Coprime q.1 m :=
    q.2.coprime_iff_not_dvd.mpr hq
  have hnum : Nat.Coprime ((q.1 : ℚ).num.natAbs) m := by
    simpa only [Rat.num_natCast, Int.natAbs_natCast] using hcop
  have hden : Nat.Coprime ((q.1 : ℚ).den) m := by
    simpa only [Rat.den_natCast] using Nat.coprime_one_left m
  calc
    (RayClass.rationalResidueUnit m
        (RayClass.positiveRationalIdealGenerator
          (toPrincipalIdeal (𝓞 ℚ) ℚ
            (Units.mk0 (q.1 : ℚ)
              (by exact_mod_cast q.2.ne_zero)))) _ _ : ZMod m) =
        (RayClass.rationalResidueUnit m (q.1 : ℚ)
          hnum hden : ZMod m) :=
      congrArg Units.val
        (RayClass.rationalResidueUnit_congr
          m hgen _ _ hnum hden)
    _ = (ZMod.unitOfCoprime q.1 hcop : ZMod m) := by
      simpa only [ZMod.coe_unitOfCoprime] using
        RayClass.rationalResidueUnit_natCast m q.1 hcop

/-- The canonical normalized finite prime idèle class at `q ∤ m` has
direct residue `q` under the rational ray-class equivalence with
`(ZMod m)ˣ`. -/
@[simp]
theorem rationalRayClassGroupEquivZModUnits_finitePrimeIdeleClass
    (m : ℕ) (hm : m ≠ 0)
    (q : Nat.Primes) (hq : ¬ q.1 ∣ m) :
    RayClass.rationalRayClassGroupEquivZModUnits m hm
        (QuotientGroup.mk'
          (RayClass.Modulus.congruenceSubgroup
            (RayClass.rationalModulus m))
          (QuotientGroup.mk'
            (IdeleGroup.principalSubgroup ℚ)
            (finitePrimeIdele
              (RayClass.rationalPrime q)))) =
      ZMod.unitOfCoprime q.1
        (q.2.coprime_iff_not_dvd.mpr hq) := by
  let hv :
      RayClass.rationalPrime q ∉
        (RayClass.rationalModulus m).finitePart.support :=
    rationalPrime_not_mem_rationalModulus_support
      m hm q hq
  let a :
      RayClass.idelePrimeToModulusSubgroup
        (RayClass.rationalModulus m) :=
    ⟨finitePrimeIdele (RayClass.rationalPrime q),
      finitePrimeIdele_mem_idelePrimeToModulusSubgroup
        (RayClass.rationalModulus m)
        (RayClass.rationalPrime q) hv⟩
  change
    RayClass.idealRayClassGroupEquivZModUnits m hm
        (RayClass.rayClassGroupEquivIdealRayClassGroup
          (RayClass.rationalModulus m)
          (QuotientGroup.mk'
            (RayClass.Modulus.congruenceSubgroup
              (RayClass.rationalModulus m))
            (QuotientGroup.mk'
              (IdeleGroup.principalSubgroup ℚ)
              (a : IdeleGroup ℚ)))) =
      ZMod.unitOfCoprime q.1
        (q.2.coprime_iff_not_dvd.mpr hq)
  rw [
    rayClassGroupEquivIdealRayClassGroup_mk_primeTo,
    idealRayProjection_finitePrimeIdele]
  change
    RayClass.primeToIdealResidueHom m hm
        (RayClass.primeToModulusIdeal
          (RayClass.rationalModulus m)
          (RayClass.rationalPrime q) hv) =
      ZMod.unitOfCoprime q.1
        (q.2.coprime_iff_not_dvd.mpr hq)
  exact primeToIdealResidueHom_rationalPrime m hm q hq

end GlobalClassFields
end GlobalClassFieldTheory
