/-
Copyright (c) 2026 Naganori Yamaguchi (https://github.com/n-yamaguchi-0729). All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Naganori Yamaguchi (assisted by OpenAI Codex)
-/

import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.EmbedsInRayClassFieldIffConductorLe
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.EmbedsInEveryRayClassFieldRealization
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.AbelianConductorFiniteUnramified
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.AbelianConductorFiniteSupport
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.AbelianConductorFiniteNormCriterion
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.AbelianConductorTameCriterion
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.AbelianConductorFiniteExponentIsLeast
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.AbelianConductorRayClassFieldLe
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.AbelianConductorRealRamification
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.IsAbelianConductorUnique
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.IsRayCongruentOfLe
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.NarrowRayClassGroupEquivNarrowClassGroup
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.OrdinaryNarrowModuliEqOfNoReal
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.OrdinaryRayClassGroupEquivClassGroup
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.ExistsAbelianConductor
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.ExistsUniqueAbelianConductor
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.FractionalIdealNormPrimeExponent
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.RayClassGroupFinite
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.RayClassIdealNormImageLeArtinKer
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.RayClassIdealNormImageEqArtinKer
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.RayClassIdealArtinKerEqNormRangeSupPrincipal
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.RayClassGroupHomExtFinitePrime
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.RayClassFieldDegree
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.RayClassFieldPrimeSplitting
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.RayClassFieldReciprocity
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.RayArtinModulusProjection
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.ExistsRayArtinModulusProjection
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.RayClassFieldModulusMonotone
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.RayClassIdealModulusProjectionPrime
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.RayClassIdealModulusProjectionSurjective
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.RayLocalHigherUnitAntitone
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.RayLocalHigherUnitMembership
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.RayLocalHigherUnitOpen
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.RayLocalHigherUnitOneAdd
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.RayLocalHigherUnitZero
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.RayClassSubgroupPrimeInertiaDegree
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.RayClassSubgroupDegree
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.RayClassSubgroupExistence
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.RayClassSubgroupEmbedding
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.RayClassSubgroupFieldAntitone
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.RayClassSubgroupRealizationEq
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.RayClassSubgroupRealizationEquiv
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.RayClassSubgroupPrimeSplitting
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.RayClassSubgroupQuotient
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.RayClassSubgroupQuotientEquivMk
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.RayPrincipalIdealMembership
import ClassFieldTheory.Theorems.ConductorsAndRayClassFields.RayPrincipalIdealPrimeTo

set_option autoImplicit false

/-!
# Conductors and ray class fields

This `All` module collects the implementation-independent finite class-field
correspondence for ray-class subgroups, full ray class fields, their degree
and prime-splitting formulas, and conductor minimality.  Each theorem has its
own leaf module.
-/
