/-
Copyright (c) 2026 Naganori Yamaguchi (https://github.com/n-yamaguchi-0729). All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Naganori Yamaguchi (assisted by OpenAI Codex)
-/

import ClassFieldTheory.LocalClassFieldTheory.LubinTateApplication.EqualCharacteristicRealFilteredComparison
import ClassFieldTheory.LocalClassFieldTheory.LubinTateApplication.EqualCharacteristicTransportedArtinComparison
import ClassFieldTheory.LocalClassFieldTheory.LubinTateApplication.EqualCharacteristicTransportedFixedFieldComparison
import ClassFieldTheory.LocalClassFieldTheory.LubinTateApplication.EqualCharacteristicTransportedLevelTower
import ClassFieldTheory.LocalClassFieldTheory.LubinTateApplication.EqualCharacteristicTransportedRealFilteredComparison
import ClassFieldTheory.LocalClassFieldTheory.LubinTateApplication.EqualCharacteristicTransportedUpperRamification
import ClassFieldTheory.LocalClassFieldTheory.LubinTateApplication.EqualCharacteristicTransportedUpperRestriction
import ClassFieldTheory.LocalClassFieldTheory.LubinTateApplication.EqualCharacteristicUpperFiltration
import ClassFieldTheory.LocalClassFieldTheory.LubinTateApplication.LaurentPrincipalUnitTransport
import ClassFieldTheory.LocalClassFieldTheory.LubinTateApplication.LubinTateTransport
import ClassFieldTheory.LocalClassFieldTheory.LubinTateApplication.NormIndex
import ClassFieldTheory.LocalClassFieldTheory.LubinTateApplication.NormSubgroup
import ClassFieldTheory.LocalClassFieldTheory.LubinTateApplication.PadicMultiplicativeArtinComparison
import ClassFieldTheory.LocalClassFieldTheory.LubinTateApplication.StandardArtinComparison
import ClassFieldTheory.LocalClassFieldTheory.LubinTateApplication.StandardFilteredArtinComparison
import ClassFieldTheory.LocalClassFieldTheory.LubinTateApplication.StandardFixedFieldComparison
import ClassFieldTheory.LocalClassFieldTheory.LubinTateApplication.StandardNormIndex
import ClassFieldTheory.LocalClassFieldTheory.LubinTateApplication.StandardNormSubgroupExact
import ClassFieldTheory.LocalClassFieldTheory.LubinTateApplication.StandardSubgroupIndex
import ClassFieldTheory.LocalClassFieldTheory.LubinTateApplication.TransportedNormSubgroupExact

set_option autoImplicit false

/-!
# Lubin--Tate application to local class field theory

This is the dependency boundary between reusable Lubin--Tate theory and its
local-class-field-theory application.  Finite local reciprocity identifies
the exact norm subgroup both for the canonical characteristic-independent
standard levels and for the transported Laurent-series model.  The lower
`LubinTate` public root and all modules below it remain independent of
`LocalClassFieldTheory`.
-/
