/-
Copyright (c) 2026 Naganori Yamaguchi (https://github.com/n-yamaguchi-0729). All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Naganori Yamaguchi (assisted by OpenAI Codex)
-/

import ClassFieldTheory.AlgebraicNumberTheory.RayClass.Ideal

set_option autoImplicit false

/-!
# Prime generation of ray ideal classes

The fractional ideals prime to a modulus are generated by their prime ideals
away from the modulus.  This is the algebraic input for comparing
Frobenius-normalized ray reciprocity maps.
-/

open scoped Classical NumberField
open NumberField IsDedekindDomain

noncomputable section

namespace RayClass

universe u v

/-- Two homomorphisms out of the prime-to-modulus fractional ideal group
agree if they agree on each prime ideal away from the modulus. -/
theorem primeToModulusIdeals_hom_ext
    {K : Type u} [Field K] [NumberField K]
    (m : RayClass.Modulus K)
    {G : Type v} [CommGroup G]
    (f g : RayClass.primeToModulusIdeals m →* G)
    (hprime : ∀ (v : HeightOneSpectrum (𝓞 K))
      (hv : v ∉ m.finitePart.support),
        f (RayClass.primeToModulusIdeal m v hv) =
          g (RayClass.primeToModulusIdeal m v hv)) :
    f = g := by
  let P := RayClass.primeToModulusIdeals m
  let p (v : HeightOneSpectrum (𝓞 K)) : P :=
    if hv : v ∉ m.finitePart.support then
      RayClass.primeToModulusIdeal m v hv else 1
  have hp (v : HeightOneSpectrum (𝓞 K)) : f (p v) = g (p v) := by
    by_cases hv : v ∉ m.finitePart.support
    · simpa only [p, dite_eq_left hv] using hprime v hv
    · simp only [p, dite_eq_right hv, map_one]
  apply MonoidHom.ext
  intro I
  let c := FractionalIdealGroup.countVector (I : FractionalIdealGroup K)
  have hfactor :
      FractionalIdealGroup.factorization (Multiplicative.ofAdd c) =
        (I : FractionalIdealGroup K) := by
    apply FractionalIdealGroup.ext_count
    intro v
    rw [FractionalIdealGroup.count_factorization]
    exact FractionalIdealGroup.countVector_apply (I : FractionalIdealGroup K) v
  have hI : I = c.prod (fun v e => p v ^ e) := by
    apply Subtype.ext
    change (I : FractionalIdealGroup K) =
      (P.subtype : P →* FractionalIdealGroup K)
        (c.prod (fun v e => p v ^ e))
    rw [← hfactor]
    change FractionalIdealGroup.factorization (Multiplicative.ofAdd c) =
      (P.subtype : P →* FractionalIdealGroup K)
        (c.support.prod (fun v => p v ^ c v))
    rw [map_prod]
    change c.support.prod
        (fun v => FractionalIdealGroup.prime v ^ c v) =
      c.support.prod
        (fun v => (P.subtype : P →* FractionalIdealGroup K) (p v ^ c v))
    apply Finset.prod_congr rfl
    intro v hv
    have hv' : v ∉ m.finitePart.support := by
      intro hvm
      exact (Finsupp.mem_support_iff.mp hv) (I.property v hvm)
    rw [map_zpow]
    change FractionalIdealGroup.prime v ^ c v =
      (p v : FractionalIdealGroup K) ^ c v
    simp only [p, dite_eq_left hv', RayClass.primeToModulusIdeal_coe]
  rw [hI]
  change f (c.support.prod (fun v => p v ^ c v)) =
    g (c.support.prod (fun v => p v ^ c v))
  rw [map_prod, map_prod]
  apply Finset.prod_congr rfl
  intro v _
  rw [map_zpow, map_zpow, hp]

end RayClass
