/-
Copyright (c) 2026 Naganori Yamaguchi (https://github.com/n-yamaguchi-0729). All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Naganori Yamaguchi (assisted by OpenAI Codex)
-/

import ClassFieldTheory.AbstractClassFieldTheory.Reciprocity.ClassField
import ClassFieldTheory.AbstractClassFieldTheory.Reciprocity.ClassFieldAxiom
import ClassFieldTheory.AbstractClassFieldTheory.Reciprocity.ClassFieldCandidate
import ClassFieldTheory.AbstractClassFieldTheory.Reciprocity.Construction.All
import ClassFieldTheory.AbstractClassFieldTheory.Reciprocity.Core
import ClassFieldTheory.AbstractClassFieldTheory.Reciprocity.CyclicNormQuotient
import ClassFieldTheory.AbstractClassFieldTheory.Reciprocity.FieldRepresentation
import ClassFieldTheory.AbstractClassFieldTheory.Reciprocity.FiniteAbelianClassification
import ClassFieldTheory.AbstractClassFieldTheory.Reciprocity.FiniteAbelianSubextension
import ClassFieldTheory.AbstractClassFieldTheory.Reciprocity.FiniteGaloisSubextension
import ClassFieldTheory.AbstractClassFieldTheory.Reciprocity.IntermediateExtension
import ClassFieldTheory.AbstractClassFieldTheory.Reciprocity.Main
import ClassFieldTheory.AbstractClassFieldTheory.Reciprocity.MaximalUnramifiedReciprocity
import ClassFieldTheory.AbstractClassFieldTheory.Reciprocity.MaximalUnramifiedSymbol
import ClassFieldTheory.AbstractClassFieldTheory.Reciprocity.NormContinuity
import ClassFieldTheory.AbstractClassFieldTheory.Reciprocity.NormTopology
import ClassFieldTheory.AbstractClassFieldTheory.Reciprocity.NormTopologyCharacterization
import ClassFieldTheory.AbstractClassFieldTheory.Reciprocity.ProfiniteAPI
import ClassFieldTheory.AbstractClassFieldTheory.Reciprocity.Reduction
import ClassFieldTheory.AbstractClassFieldTheory.Reciprocity.Sylow
import ClassFieldTheory.AbstractClassFieldTheory.Reciprocity.TotallyRamified
import ClassFieldTheory.AbstractClassFieldTheory.Reciprocity.TotallyRamifiedCase.All
import ClassFieldTheory.AbstractClassFieldTheory.Reciprocity.ValuationContinuity

set_option autoImplicit false

/-!
# Abstract reciprocity

Public aggregate for the class-formation reciprocity theorem and the canonical
construction and naturality of its reciprocity maps.
-/
