/-
Copyright (c) 2026 Naganori Yamaguchi (https://github.com/n-yamaguchi-0729). All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Naganori Yamaguchi (assisted by OpenAI Codex)
-/

import ClassFieldTheory.Theorems.HasseArf.HasseArf
import ClassFieldTheory.Theorems.HasseArf.HerbrandFunctionAtLowerIndexStrictMono
import ClassFieldTheory.Theorems.HasseArf.HerbrandFunctionAtLowerIndexDifference
import ClassFieldTheory.Theorems.HasseArf.HerbrandFunctionAtLowerIndexNatOfJump
import ClassFieldTheory.Theorems.HasseArf.HerbrandFunctionCanonical
import ClassFieldTheory.Theorems.HasseArf.HerbrandFunctionInverseHerbrandFunction
import ClassFieldTheory.Theorems.HasseArf.HerbrandFunctionNat
import ClassFieldTheory.Theorems.HasseArf.InverseHerbrandFunctionHerbrandFunction
import ClassFieldTheory.Theorems.HasseArf.IsUpperRamificationJumpInt
import ClassFieldTheory.Theorems.HasseArf.LowerRamificationGroupAntitone
import ClassFieldTheory.Theorems.HasseArf.LowerRamificationGroupEventuallyBot
import ClassFieldTheory.Theorems.HasseArf.LowerRamificationGroupNormal
import ClassFieldTheory.Theorems.HasseArf.LowerRamificationGroupZeroEqInertia
import ClassFieldTheory.Theorems.HasseArf.RealLowerRamificationGroupCanonical
import ClassFieldTheory.Theorems.HasseArf.RealLowerRamificationGroupNat
import ClassFieldTheory.Theorems.HasseArf.RealLowerRamificationGroupNormal
import ClassFieldTheory.Theorems.HasseArf.RealAndUpperRamificationGroupNormal
import ClassFieldTheory.Theorems.HasseArf.UpperRamificationGroupAntitone
import ClassFieldTheory.Theorems.HasseArf.UpperRamificationGroupCanonical
import ClassFieldTheory.Theorems.HasseArf.UpperRamificationGroupAfter
import ClassFieldTheory.Theorems.HasseArf.UpperRamificationGroupEventuallyBot

set_option autoImplicit false

/-! Public Hasse--Arf theorem and basic lower-filtration identities. -/
