/-
Copyright (c) 2026 Naganori Yamaguchi (https://github.com/n-yamaguchi-0729). All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Naganori Yamaguchi (assisted by OpenAI Codex)
-/

import ClassFieldTheory.Theorems.LocalClassFieldTheory.FiniteAbelianLocalExistence
import ClassFieldTheory.Theorems.LocalClassFieldTheory.FiniteAbelianLocalExistenceOrderIso
import ClassFieldTheory.Theorems.LocalClassFieldTheory.FiniteAbelianLocalReciprocity
import ClassFieldTheory.Theorems.LocalClassFieldTheory.FiniteAbelianLocalReciprocityFamily
import ClassFieldTheory.Theorems.LocalClassFieldTheory.FiniteAbelianLocalReciprocityFamilyArithmeticFrobenius
import ClassFieldTheory.Theorems.LocalClassFieldTheory.FiniteAbelianLocalReciprocityFamilyExt
import ClassFieldTheory.Theorems.LocalClassFieldTheory.FiniteAbelianLocalReciprocityFamilyUnramifiedNormalization
import ClassFieldTheory.Theorems.LocalClassFieldTheory.FiniteAbelianLocalReciprocityUnramifiedNormalization
import ClassFieldTheory.Theorems.LocalClassFieldTheory.FiniteAbelianLocalReciprocityUnramifiedHomExt
import ClassFieldTheory.Theorems.LocalClassFieldTheory.FiniteAbelianLocalReciprocityUnramifiedFamilyExt
import ClassFieldTheory.Theorems.LocalClassFieldTheory.FiniteAbelianLocalReciprocityIndex
import ClassFieldTheory.Theorems.LocalClassFieldTheory.FiniteAbelianLocalReciprocityQuotient
import ClassFieldTheory.Theorems.LocalClassFieldTheory.FiniteAbelianLocalReciprocityQuotientEquivMk
import ClassFieldTheory.Theorems.LocalClassFieldTheory.FiniteAbelianLocalReciprocityQuotientEquivOfArtin
import ClassFieldTheory.Theorems.LocalClassFieldTheory.FiniteAbelianLocalReciprocityTower
import ClassFieldTheory.Theorems.LocalClassFieldTheory.FieldNormSubgroupFiniteIndex
import ClassFieldTheory.Theorems.LocalClassFieldTheory.FieldNormSubgroupIsOpen
import ClassFieldTheory.Theorems.LocalClassFieldTheory.FieldNormSubgroupRingEquiv
import ClassFieldTheory.Theorems.LocalClassFieldTheory.FieldNormSubgroupTower
import ClassFieldTheory.Theorems.LocalClassFieldTheory.MemFieldNormSubgroupIff
import ClassFieldTheory.Theorems.LocalClassFieldTheory.ProfiniteLocalReciprocity

set_option autoImplicit false

/-!
# Finite abelian local class field theory

This module gathers the public local reciprocity, local existence, and
norm-subgroup statements.  The theorem statements use Mathlib and the public
definitions layer; their proofs may import implementation modules.
-/
